// Explicit local real-archive acceptance; reads only an already running service.
import { chromium, expect } from '@playwright/test';
import { readFile, stat, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import path from 'node:path';
const directory = process.argv[2];
if (!directory || !path.isAbsolute(directory)) throw new Error('Pass absolute private evidence directory');
const root = path.resolve(directory, '../..');
const indexFile = path.join(directory, 'archive-index.json');
const index = JSON.parse(await readFile(indexFile, 'utf8'));
const capture = JSON.parse(await readFile(path.join(directory, 'sample-capture.json'), 'utf8'));
const previous = JSON.parse(await readFile(path.join(root, '.local/real-gaussian-installed-acceptance/expectations.json'), 'utf8'));
const files = [indexFile, previous.database, ...capture.files.map(f => f.local_file)];
async function fingerprint() {
  return Promise.all(files.map(async file => { const s = await stat(file, { bigint: true }); return { sha256: createHash('sha256').update(await readFile(file)).digest('hex'), size: String(s.size), inode: String(s.ino), mtime_ns: String(s.mtimeNs), ctime_ns: String(s.ctimeNs) }; }));
}
const before = await fingerprint();
// Token was just generated by this task's preview launcher. Never print/persist it.
const token = execFileSync('pbpaste', { encoding: 'utf8' }).trim();
if (!/^[A-Za-z0-9_-]{32,256}$/.test(token)) throw new Error('Preview token is no longer on clipboard');
const origin = 'http://127.0.0.1:8766';
const get = async url => { const r = await fetch(origin + url, { headers: { Authorization: `Bearer ${token}` } }); expect(r.status).toBe(200); return r.json(); };
const record = index.records[0];
expect((await get('/api/archives')).items).toHaveLength(1);
expect((await get('/api/archives/' + record.archive_id)).data).toEqual(record);
for (const [url, dto] of Object.entries(previous.expected)) expect(await get(url)).toEqual(dto);
const parser = JSON.parse(await readFile(path.join(directory, 'sample-parse-probe.json'), 'utf8'));
expect(record.summary.energy_hartree).toBe(parser.facts.final_energy_hartree);
expect(record.summary.normal_count).toBe(parser.facts.normal_termination_count);
expect(record.summary.error_count).toBe(parser.facts.error_termination_count);
expect(record.summary.optimization).toBe(parser.facts.optimization_completed_marker);
expect(record.summary.stationary_point).toBe(parser.facts.stationary_point_marker);
expect(parser.facts.frequency_count).toBe(0);
expect(record.summary.frequency_count).toBeNull(); expect(record.summary.imaginary_count).toBeNull();
const browser = await chromium.launch({ channel: 'chrome' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], methods = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('request', r => { if (r.url().includes('/api/')) methods.push(r.method()); });
  await page.goto(origin + '/#/archives');
  await page.getByLabel('只读访问令牌').fill(token);
  await page.getByRole('button', { name: '连接数据源' }).click();
  await page.getByRole('link', { name: record.title }).click();
  const facts = page.getByTestId('archive-facts');
  const datum = label => facts.locator('.field').filter({ has: page.locator('dt', { hasText: label }) }).locator('dd');
  await expect(datum('最终能量 / Hartree')).toHaveText(String(record.summary.energy_hartree));
  await expect(datum('正常 / 错误终止次数')).toHaveText(`${record.summary.normal_count} / ${record.summary.error_count}`);
  await expect(datum('日志终止标记')).toHaveText('正常终止');
  await expect(datum('优化完成标记')).toHaveText('已记录');
  await expect(datum('驻点标记')).toHaveText('已记录');
  await expect(datum(/^频率数量$/)).toHaveText('未记录');
  await expect(datum('虚频数量')).toHaveText('未知（未记录频率）');
  expect(await page.getByTestId('archive-input').textContent()).toBe(record.input.text);
  for (const a of record.artifacts) {
    await expect(page.getByText(a.logical_name, { exact: true })).toBeVisible();
    await expect(page.getByText(`SHA-256 ${a.sha256}`, { exact: true })).toBeVisible();
  }
  await expect(page.getByText('Core Attempt / 实时状态 / 科学验收 / Review：不可用')).toBeVisible();
  await page.screenshot({ path: path.join(directory, 'archive-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(directory, 'archive-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: '断开', exact: true }).click();
  await expect(facts).toHaveCount(0); await expect(page.getByTestId('archive-input')).toHaveCount(0);
  expect(errors).toEqual([]); expect(methods.every(x => x === 'GET')).toBe(true);
  expect(await fingerprint()).toEqual(before);
  const receipt = { schema: 'autog-legacy-archive-acceptance/1', status: 'PASS', observed_at: new Date().toISOString(),
    archive_sha256: before[0].sha256, unchanged_source_files: files.length, core_routes_unchanged: Object.keys(previous.expected).length,
    archive_http_routes: 2, browser_errors: errors.length, only_get: true, input_and_hashes_match: true,
    summary_matches_public_parser: true, desktop_and_mobile: true, core_authority_created: false, scientific_acceptance_inferred: false,
    runtime: 'source frontend candidate with pinned installed backend; not the prior frozen frontend wheel' };
  await writeFile(path.join(directory, 'acceptance.json'), JSON.stringify(receipt, null, 2) + '\n', { flag: 'wx' });
  console.log(JSON.stringify(receipt));
} finally { await browser.close(); }
