import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
test.skip(process.env.AUTOG_TEST_MODE_REVIEW!=='1','requires isolated synthetic review store');
const endpoint='/api/attempts/synthetic-mode-review/mode-review';
async function connect(page:Page){await page.goto('/#/attempts/synthetic-mode-review');await page.getByLabel('只读访问令牌').fill('browser-test-only-'+'0'.repeat(32));await page.getByRole('button',{name:'连接数据源'}).click();await page.getByRole('button',{name:'结构与结果',exact:true}).click();await page.getByTestId('scientific-validation').locator('summary').first().click();await expect(page.getByLabel('模式确认者')).toBeVisible();}
async function prepare(page:Page,name:string){const card=page.getByTestId('scientific-validation');await card.getByRole('button',{name:'读取虚频位移'}).click();await card.getByRole('button',{name:'查看虚频模式 1'}).click();await expect(card.getByRole('checkbox')).toBeEnabled();await page.getByLabel('模式确认者').fill(name);await card.getByRole('checkbox').check();}
test('only explicit reviewed mode produces an independent persistent record, including on mobile',async({page})=>{
 const writes:string[]=[];page.on('request',r=>{if(r.url().includes('/api/')&&r.method()!=='GET')writes.push(r.url());});
 await page.setViewportSize({width:390,height:844});await connect(page);const card=page.getByTestId('scientific-validation');
 await expect(card.getByRole('checkbox')).toBeDisabled();await expect(card.getByRole('button',{name:'记录目标振动方向确认'})).toBeDisabled();expect(writes).toEqual([]);
 await prepare(page,'Synthetic reviewer <script>');await page.getByLabel('模式确认备注').fill('Synthetic test only — C1/C2 direction');
 await card.getByRole('button',{name:'记录目标振动方向确认'}).click();await expect(card).toContainText('目标振动方向已记录 · 非 TS 接受');await expect(card.locator('.mode-review-record')).toContainText('Synthetic reviewer <script>');
 await page.getByTestId('human-mode-review').screenshot({path:'../.local/human-mode-review/synthetic-record-mobile.png'});expect(writes).toHaveLength(1);expect(writes[0]).toContain(endpoint);await expect(card).toContainText('TS candidate');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.reload();await expect(page.getByLabel('只读访问令牌')).toBeVisible();await page.getByLabel('只读访问令牌').fill('browser-test-only-'+'0'.repeat(32));await page.getByRole('button',{name:'连接数据源'}).click();await page.getByRole('button',{name:'结构与结果',exact:true}).click();await page.getByTestId('scientific-validation').locator('summary').first().click();await expect(page.getByTestId('human-mode-review')).toContainText('Synthetic reviewer <script>');await expect(page.getByLabel('模式确认者')).toHaveValue('');expect(writes).toHaveLength(1);
});
test('lost committed response retries exact UUID and creates just one record',async({page})=>{
 let dropped=false;const bodies:string[]=[];
 await page.route('**'+endpoint,async route=>{if(route.request().method()!=='POST'){await route.continue();return;}bodies.push(route.request().postData()!);const response=await route.fetch();if(!dropped){dropped=true;expect(response.status()).toBe(200);await route.abort();}else await route.fulfill({response});});
 await connect(page);await prepare(page,'Synthetic lost-response reviewer');await page.getByRole('button',{name:'记录目标振动方向确认'}).click();await expect(page.getByRole('alert')).toContainText('未能确认写入结果');expect(bodies).toHaveLength(1);await expect(page.getByLabel('模式确认者')).toBeDisabled();await page.getByRole('button',{name:'重试原确认请求'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('.mode-review-record').filter({hasText:'Synthetic lost-response reviewer'})).toHaveCount(1);expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);
});
test('mismatched displayed displacement digest cannot enable confirmation',async({page})=>{
 await page.route('**'+endpoint,async route=>{const response=await route.fetch(),packet=await response.json();packet.target.displacements_sha256='f'.repeat(64);packet.other_target_count+=packet.records.length;packet.records=[];await route.fulfill({json:packet});});
 await connect(page);const card=page.getByTestId('scientific-validation');await card.getByRole('button',{name:'读取虚频位移'}).click();await card.getByRole('button',{name:'查看虚频模式 1'}).click();await expect(page.getByTestId('vibration-controls')).toContainText('模式 1');await expect(card.getByRole('checkbox')).toBeDisabled();await expect(card.getByRole('button',{name:'记录目标振动方向确认'})).toBeDisabled();
});
test('changed server target refuses the explicit command and does not display success',async({page})=>{
 await page.route('**'+endpoint,async route=>{if(route.request().method()==='POST'){const cmd=JSON.parse(route.request().postData()!);cmd.target_sha256='f'.repeat(64);const response=await route.fetch({postData:cmd});expect(response.status()).toBe(409);await route.fulfill({response});}else await route.continue();});
 await connect(page);await prepare(page,'Synthetic stale-target reviewer');await page.getByRole('button',{name:'记录目标振动方向确认'}).click();await expect(page.getByRole('alert')).toContainText('未能确认写入结果');await expect(page.locator('.mode-review-record').filter({hasText:'Synthetic stale-target reviewer'})).toHaveCount(0);await page.getByRole('button',{name:'只读核对已保存记录'}).click();await expect(page.getByLabel('模式确认者')).toBeVisible();await expect(page.locator('.mode-review-record').filter({hasText:'Synthetic stale-target reviewer'})).toHaveCount(0);
});
test('view switching stops animation and preserves an uncertain confirmation request',async({page})=>{
 const bodies:string[]=[];let dropped=false;
 await page.route('**'+endpoint,async route=>{if(route.request().method()!=='POST'){await route.continue();return;}bodies.push(route.request().postData()!);const response=await route.fetch();if(!dropped){dropped=true;await route.abort();}else await route.fulfill({response});});
 await connect(page);await prepare(page,'Synthetic tab-switch reviewer');await page.getByRole('button',{name:'记录目标振动方向确认'}).click();await expect(page.getByRole('alert')).toContainText('未能确认写入结果');
 await page.getByTestId('scientific-validation').locator('summary').first().click();await expect(page.getByLabel('模式确认者')).toBeHidden();await page.getByTestId('scientific-validation').locator('summary').first().click();await expect(page.getByLabel('模式确认者')).toHaveValue('Synthetic tab-switch reviewer');await page.getByRole('button',{name:'运行与诊断',exact:true}).click();await expect(page.getByTestId('vibration-controls')).toHaveCount(0);await page.getByRole('button',{name:'结构与结果',exact:true}).click();await expect(page.getByLabel('模式确认者')).toHaveValue('Synthetic tab-switch reviewer');await expect(page.getByLabel('模式确认者')).toBeDisabled();
 await page.getByRole('button',{name:'查看虚频模式 1'}).click();await page.getByTestId('scientific-validation').getByRole('checkbox').check();await page.getByRole('button',{name:'重试原确认请求'}).click();await expect(page.getByRole('alert')).toHaveCount(0);expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);await expect(page.locator('.mode-review-record').filter({hasText:'Synthetic tab-switch reviewer'})).toHaveCount(1);
});
