import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
const token='browser-test-only-'+'0'.repeat(32);
async function connect(page:Page,hash='#/projects'){await page.goto('/'+hash);await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();}
async function go(page:Page,hash:string){await page.evaluate(h=>location.hash=h,hash);}
async function candidates(page:Page){await connect(page,'#/screening');const option=page.getByLabel('项目／候选集合').locator('option').filter({hasText:'screening-fixtures'});await expect(option).toHaveCount(1);const id=(await option.getAttribute('value'))!;await page.getByLabel('项目／候选集合').selectOption(id);await expect(page.getByRole('button',{name:'screening-fixtures · candidate-0',exact:true})).toBeVisible();return id;}
test('four main destinations and legacy redirects preserve encoded project context',async({page})=>{
 await connect(page);await expect(page.getByRole('navigation',{name:'主导航'}).getByRole('link')).toHaveText(['项目','计算','分析','监控']);
 for(const [old,dest] of [['#/drafts','#/calculations?tab=new'],['#/task-center','#/calculations?tab=drafts'],['#/workflows','#/calculations?tab=runs'],['#/screening','#/analysis?tab=compare'],['#/offline-science','#/analysis?tab=irc'],['#/capabilities','#/settings?tab=capabilities'],['#/library','#/settings?tab=library'],['#/tests','#/projects?purpose=test'],['#/archives','#/projects?source=historical']]){await go(page,old);await expect.poll(()=>page.evaluate(()=>location.hash)).toBe(dest);}
 await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'计算',exact:true}).click();await expect(page.getByRole('navigation',{name:'页面分区'}).getByRole('link')).toHaveText(['运行与历史','草稿','待处理任务']);await expect(page.getByRole('link',{name:'运行与历史',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('heading',{name:'运行总览',exact:true})).toBeVisible();
 const project='测试%2F?project';await go(page,'#/results?project='+encodeURIComponent(project));await expect.poll(()=>page.evaluate(()=>new URLSearchParams(location.hash.split('?')[1]).get('project'))).toBe(project);await expect(page.getByRole('navigation',{name:'当前项目'})).toContainText(project);
});
test('single detail has combined default results and lazy evidence views and accessible export drawers',async({page})=>{
 const calls:string[]=[];page.on('request',r=>{if(r.url().includes('/api/'))calls.push(r.method()+' '+r.url());});await connect(page,'#/attempts/gaussian-normal');await expect(page.getByTestId('result-facts')).toBeVisible();await expect(page.locator('.molecule-section')).toBeVisible();await expect(page.getByTestId('execution-evidence')).toHaveCount(0);await expect(page.getByLabel('详情显示方式').getByRole('button')).toHaveText(['结构与结果','运行与诊断','来源与记录']);
 await expect(page.getByTestId('full-frequencies')).toBeVisible();await go(page,'#/attempts/gaussian-normal?view=overview');await expect(page.getByRole('button',{name:'结构与结果',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.molecule-section')).toHaveCount(1);
 await page.getByRole('button',{name:/定位原日志：频率 1/}).click();await expect(page.getByRole('button',{name:'运行与诊断',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByTestId('full-frequencies')).toBeHidden();
 await page.getByRole('button',{name:'来源与记录',exact:true}).click();await expect(page.getByTestId('result-provenance')).toBeVisible();
 await page.getByRole('button',{name:'导出结果',exact:true}).click();await expect(page.getByRole('dialog',{name:'导出结果',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'导出结果',exact:true})).toBeHidden();await expect(page.getByRole('button',{name:'导出结果',exact:true})).toBeFocused();expect(calls.every(c=>c.startsWith('GET '))).toBe(true);
});
test('project selection passes exact records to comparison and returns with filters',async({page})=>{
 const group=await candidates(page);await go(page,'#/history-projects/'+encodeURIComponent(group));await page.getByLabel('搜索项目结果',{exact:true}).fill('candidate-');await expect(page.getByLabel('选择结果 screening-fixtures · candidate-0',{exact:true})).toBeVisible();await page.getByLabel('选择结果 screening-fixtures · candidate-0',{exact:true}).check();await page.getByLabel('选择结果 screening-fixtures · candidate-1',{exact:true}).check();await page.getByRole('link',{name:'比较选中结果'}).click();await expect(page.locator('.comparison-panel')).toBeVisible();await expect(page.locator('.candidate-layout tbody tr')).toHaveCount(2);await expect(page.getByLabel('比较 screening-fixtures · candidate-0',{exact:true})).toBeChecked();
 await page.getByRole('link',{name:'打开计算详情'}).click();await expect(page.getByRole('button',{name:'结构与结果',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('link',{name:'返回刚才的列表',exact:false}).click();await expect(page.locator('.comparison-panel')).toBeVisible();await go(page,'#/history-projects/'+encodeURIComponent(group));await expect(page.getByLabel('搜索项目结果',{exact:true})).toHaveValue('candidate-');await expect(page.getByLabel('选择结果 screening-fixtures · candidate-0',{exact:true})).toBeChecked();
});
test('browser input and service draft share one destination without merging identities',async({page})=>{
 await candidates(page);await page.getByRole('button',{name:'保存计算草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await go(page,'#/drafts');await page.getByLabel('导入结构文件').setInputFiles({name:'water.xyz',mimeType:'text/plain',buffer:Buffer.from('3\nwater\nO 0 0 0\nH 0 .7 .5\nH 0 -.7 .5\n')});for(const [k,v]of [['方法 / 泛函','HF'],['基组','STO-3G'],['环境','gas'],['总电荷','0'],['自旋多重度','1'],['CPU 核数','8'],['内存 / GiB','12'],['Walltime','24:00:00']])await page.getByLabel(k,{exact:true}).fill(v);await page.getByLabel('创建 / 修改理由').fill('navigation regression');
 await go(page,'#/projects');await expect(page.getByRole('heading',{name:'项目库',exact:true})).toBeVisible();await go(page,'#/drafts');await expect(page.getByLabel('方法 / 泛函',{exact:true})).toHaveValue('HF');await expect(page.getByTestId('draft-input')).toContainText('HF/STO-3G');await page.getByLabel('我已核对结构、立体化学、电荷').check();await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存新草稿版本');await go(page,'#/calculations?tab=drafts');await expect(page.locator('.draft-origin').filter({hasText:'当前浏览器'})).toHaveCount(1);await expect(page.locator('.draft-origin').filter({hasText:'本地服务端'})).toHaveCount(1);await page.getByRole('link',{name:'继续编辑此版本'}).click();await expect(page.getByTestId('draft-input')).toContainText('HF/STO-3G');
});
test('diagnosis and repair live behind explicit actions; repair links to original result',async({page})=>{
 await candidates(page);await page.getByRole('link',{name:'打开计算详情'}).click();await expect(page.getByLabel('原 Gaussian 输入',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'运行与诊断',exact:true}).click();await page.getByRole('button',{name:'读取报错与优化轨迹'}).click();await expect(page.getByLabel('优化步骤')).toBeVisible();await page.getByRole('button',{name:'生成修复草稿',exact:true}).click();await expect(page.getByRole('dialog',{name:'生成修复草稿'})).toBeVisible();await page.getByLabel('原 Gaussian 输入',{exact:true}).setInputFiles({name:'water.gjf',mimeType:'text/plain',buffer:Buffer.from('# HF/STO-3G Opt Freq\n\nwater\n\n0 1\nO 0 0 0\nH 0 .7 .5\nH 0 -.7 .5\n\n')});await page.getByLabel('修复理由').fill('synthetic repair');await page.getByLabel('我已确认原输入与诊断来源对应').check();await page.getByRole('button',{name:'保存修复草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('修复草稿已保存');await page.keyboard.press('Escape');await go(page,'#/calculations?tab=drafts');await expect(page.locator('.task-card').filter({hasText:'修复草稿'})).toContainText('返回来源结果');
});
test('mobile navigation and three detail tabs fit small screens',async({page})=>{
 await page.setViewportSize({width:390,height:844});await connect(page,'#/attempts/gaussian-normal');for(const name of ['结构与结果','运行与诊断','来源与记录']){await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await page.screenshot({path:'test-results/navigation-mobile.png',fullPage:true});
});
test('selected Gibbs energies require matching recorded temperature for population',async({page})=>{
 await page.route('**/api/archives/*/details',async route=>{const response=await route.fetch(),d=await response.json();if(d.result.data)d.result.data.thermochemistry.sum_electronic_gibbs_hartree={value_hartree:-74.5};await route.fulfill({json:d});});
 await page.route('**/api/archives/*/conditions',async route=>{const response=await route.fetch(),d=await response.json(),detail=await(await route.fetch({url:route.request().url().replace('/conditions','/details')})).json();d.observed={source:detail.result.source.artifact,steps:[{fields:{temperature_k:[{value:298.15}]}}]};await route.fulfill({json:d});});
 await candidates(page);await page.getByLabel('比较 screening-fixtures · candidate-0',{exact:true}).check();await page.getByLabel('比较 screening-fixtures · candidate-1',{exact:true}).check();await page.getByLabel('比较能量',{exact:true}).selectOption('G');await page.getByLabel('人工可比性核对说明').fill('Synthetic same-system same-temperature comparison');await page.getByLabel('我已核对结构身份、实际条件和结果来源').check();await page.getByLabel('已核对的自由能计算温度 / K').fill('300');await expect(page.getByLabel('温度与这些 G 的计算条件一致')).toBeDisabled();await page.getByLabel('已核对的自由能计算温度 / K').fill('298.15');await page.getByLabel('温度与这些 G 的计算条件一致').check();await expect(page.locator('.comparison-panel')).toContainText('50.000%');await page.getByLabel('比较 screening-fixtures · candidate-1',{exact:true}).uncheck();await expect(page.locator('.comparison-panel')).toHaveCount(0);await page.unrouteAll({behavior:'wait'});
});
