import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
const token='browser-test-only-'+'0'.repeat(32);
async function connect(page:Page,hash:string){await page.goto('/'+hash);await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();}
async function screening(page:Page){await connect(page,'#/screening');await expect(page.getByLabel('项目／候选集合').locator('option').filter({hasText:'screening-fixtures'})).toHaveCount(1);const id=await page.getByLabel('项目／候选集合').locator('option').filter({hasText:'screening-fixtures'}).getAttribute('value');await page.getByLabel('项目／候选集合').selectOption(id!);await expect(page.getByRole('button',{name:'screening-fixtures · candidate-0',exact:true})).toBeVisible();await expect(page.locator('tbody')).toContainText('TS 候选');}
test('candidate screening uses real synthetic details, explicit comparison and durable draft',async({page})=>{
 await screening(page);await page.getByLabel('比较 screening-fixtures · candidate-0',{exact:true}).check();await page.getByLabel('比较 screening-fixtures · candidate-1',{exact:true}).check();
 await page.getByLabel('人工可比性核对说明').fill('Synthetic fixture: same method and conditions.');const confirmation=page.getByLabel('我已核对结构身份、实际条件和结果来源',{exact:false});await expect(confirmation).toBeEnabled();await confirmation.check();await expect(page.locator('.comparison-panel tbody')).toContainText('6.275');
 await page.getByRole('button',{name:'保存计算草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.getByRole('link',{name:'前往任务中心'}).click();await expect(page.locator('.task-card').filter({hasText:'screening-fixtures · candidate-0'}).first()).toBeVisible();
 await page.reload();await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();await expect(page.locator('.task-card').filter({hasText:'screening-fixtures · candidate-0'}).first()).toContainText('计算草稿');
});
test('trajectory points link energy, geometry, convergence and original log',async({page})=>{
 await screening(page);await page.getByRole('link',{name:'打开计算详情'}).click();await page.getByRole('button',{name:'运行与诊断',exact:true}).click();await page.getByRole('button',{name:'读取报错与优化轨迹'}).click();const panel=page.getByTestId('calculation-analysis');await expect(panel.getByLabel('优化步骤')).toBeVisible();const scene=await panel.locator('.analysis-structure').boundingBox(),plot=await panel.locator('.analysis-plots').boundingBox();expect(scene!.x+scene!.width).toBeLessThanOrEqual(plot!.x);expect(Math.abs(scene!.y-plot!.y)).toBeLessThan(5);await panel.getByLabel('优化步骤').selectOption('1');await expect(panel).toContainText('-75.01 Hartree');await expect(panel.getByLabel('结构来源').locator('option:checked')).toHaveText('当前优化步结构');await expect(panel.getByLabel('优化能量 / Hartree',{exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});const mobileScene=await panel.locator('.analysis-structure').boundingBox(),mobilePlot=await panel.locator('.analysis-plots').boundingBox();expect(mobileScene!.y+mobileScene!.height).toBeLessThanOrEqual(mobilePlot!.y);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.setViewportSize({width:1440,height:960});await panel.getByRole('button',{name:'播放轨迹',exact:true}).click();await expect(panel.getByRole('button',{name:'暂停轨迹',exact:true})).toBeVisible();await panel.getByRole('button',{name:'暂停轨迹',exact:true}).click();await panel.getByRole('button',{name:'定位原日志：该步能量来源',exact:true}).click();await expect(page.getByTestId('source-excerpt')).toContainText('SCF Done:');
});
test('submission requires concrete review and survives refresh without duplicate request',async({page})=>{
 await connect(page,'#/calculations?tab=queue');await page.getByRole('button',{name:'查看提交预览'}).click();const preview=page.getByRole('region',{name:'提交预览'});await expect(preview.getByRole('button',{name:'确认立即提交',exact:true})).toBeDisabled();await expect(preview).toContainText('#p hf/sto-3g');await preview.getByRole('checkbox').check();let writes=0;page.on('request',r=>{if(r.url().endsWith('/api/task-center/submit'))writes++;});await preview.getByRole('button',{name:'确认立即提交',exact:true}).click();await expect(page.locator('.task-card').filter({hasText:'已提交服务器'})).toBeVisible({timeout:12000});expect(writes).toBe(1);await page.reload();await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();await expect(page.locator('.task-card').filter({hasText:'已提交服务器'})).toHaveCount(1);expect(writes).toBe(1);
});
test('bad analysis bindings fail closed and page does not POST while browsing',async({page})=>{
 let writes=0;page.on('request',r=>{if(r.url().includes('/api/')&&r.method()==='POST')writes++;});await page.route('**/api/archives/*/analysis',async r=>{const v=await(await r.fetch()).json();v.data.source.sha256='0'.repeat(64);await r.fulfill({json:v});});await screening(page);await page.getByRole('link',{name:'打开计算详情'}).click();await page.getByRole('button',{name:'运行与诊断',exact:true}).click();await page.getByRole('button',{name:'读取报错与优化轨迹'}).click();await expect(page.getByTestId('calculation-analysis')).toContainText('轨迹来源不一致');expect(writes).toBe(0);
});
test('mobile candidate and task pages fit viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});await screening(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.getByRole('link',{name:'前往任务中心'}).click();await expect(page.getByRole('heading',{name:'计算草稿',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
