import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
const token='browser-test-only-'+'0'.repeat(32),water='3\nwater\nO 0 0 0\nH 0 .7 .5\nH 0 -.7 .5\n';
async function connect(page:Page,hash:string){await page.goto('/'+hash);await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();}
async function fillDraft(page:Page){await page.getByLabel('导入结构文件').setInputFiles({name:'water.xyz',mimeType:'text/plain',buffer:Buffer.from(water)});for(const [label,value] of [['计算标题','water'],['方法 / 泛函','HF'],['基组','STO-3G'],['环境','gas'],['总电荷','0'],['自旋多重度','1'],['CPU 核数','8'],['内存 / GiB','12'],['Walltime','24:00:00']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel('创建 / 修改理由').fill('明确条件，准备离线输入');await page.getByLabel('我已核对结构、立体化学、电荷').check();}
test('draft persists immutable revisions and downloads exact Gaussian input without API writes',async({page})=>{
 const writes:string[]=[];page.on('request',r=>{if(r.method()!=='GET'&&r.url().includes('/api/'))writes.push(r.url());});await connect(page,'#/drafts');await fillDraft(page);await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存新草稿版本');await page.getByLabel('方法 / 泛函',{exact:true}).fill('B3LYP');await expect(page.getByLabel('我已核对结构、立体化学、电荷')).not.toBeChecked();await page.getByLabel('创建 / 修改理由').fill('比较方法草稿');await page.getByLabel('我已核对结构、立体化学、电荷').check();await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect.poll(()=>page.evaluate(()=>new Promise<number>((resolve,reject)=>{const r=indexedDB.open('autog-local-workbench-v1',1);r.onsuccess=()=>{const d=r.result,q=d.transaction('records').objectStore('records').count();q.onsuccess=()=>{resolve(q.result);d.close();};q.onerror=reject;};}))).toBe(2);
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'导出 Gaussian 输入',exact:true}).click();expect((await dl).suggestedFilename()).toBe('water.gjf');await page.reload();await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();await expect.poll(()=>page.evaluate(()=>new Promise<number>((resolve,reject)=>{const r=indexedDB.open('autog-local-workbench-v1',1);r.onsuccess=()=>{const d=r.result,q=d.transaction('records').objectStore('records').count();q.onsuccess=()=>{resolve(q.result);d.close();};q.onerror=reject;};}))).toBe(2);await page.evaluate(()=>location.hash='#/calculations?tab=drafts');await page.getByRole('link',{name:'继续编辑此版本'}).first().click();await expect(page.getByTestId('draft-input')).toContainText('B3LYP/STO-3G');expect(writes).toEqual([]);
});
test('malformed or tampered notebook import does not replace stored versions',async({page})=>{await connect(page,'#/drafts');await fillDraft(page);await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存新草稿版本');await page.evaluate(()=>location.hash='#/calculations?tab=drafts');await page.getByLabel('恢复笔记包').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schema:'autog-local-notebook/1',records:[{schema:'autog-local-note/1',id:'broken'}]}))});await expect(page.getByRole('alert')).toContainText('记录字段不正确');await expect(page.locator('.draft-shelf .task-card')).toHaveCount(1);});
test('IRC point selection links structure and energy and invalid trajectory is rejected',async({page})=>{await connect(page,'#/offline-science');const g={units:'angstrom',atoms:[{center:1,atomic_number:1,x:0,y:0,z:0}]};const data={schema:'autog-irc-trajectory/1',coordinate_units:'point-index',points:[0,1].map(i=>({branch:'forward',point:i,coordinate:i,energy_hartree:-1-i*.01,geometry:g}))};await page.getByLabel('导入 IRC 轨迹').setInputFiles({name:'irc.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.getByRole('button',{name:'IRC forward 点 1',exact:true}).click();await expect(page.getByText('当前点：',{exact:false})).toContainText('E=-1.01');await expect(page.getByLabel('结构来源').locator('option:checked')).toHaveText('当前 IRC 点结构');await page.getByLabel('导入 IRC 轨迹').setInputFiles({name:'bad.xyz',mimeType:'text/plain',buffer:Buffer.from(water+water)});await expect(page.getByRole('alert')).toContainText('XYZ 注释必须');await expect(page.getByRole('img',{name:'IRC 能量曲线'})).toHaveCount(0);});
test('GoodVibes populations require explicit matching temperature, selected set and review',async({page})=>{await connect(page,'#/analysis?tab=thermo');await page.getByLabel('导入 GoodVibes 结果').setInputFiles({name:'goodvibes.dat',mimeType:'text/plain',buffer:Buffer.from('Structure E G(T) qh-G(T)\n********\no c1 -75 -74.9 -74.9\no c2 -75 -74.9 -74.9\n********\n')});await page.getByLabel('纳入 c1',{exact:true}).check();await page.getByLabel('纳入 c2',{exact:true}).check();const c=page.getByLabel('我已核对以上条件');await expect(c).toBeDisabled();await page.getByLabel('该表计算温度 / K').fill('298.15');await page.getByLabel('核对说明：组成').fill('同一体系、方法、温度和标准态，去重集合。');await c.check();await expect(page.locator('tbody')).toContainText('50.000%');await page.getByLabel('该表计算温度 / K').fill('300');await expect(c).not.toBeChecked();await expect(page.locator('tbody')).not.toContainText('%');});
test('capabilities reflect actual disabled execution and new pages fit mobile width',async({page})=>{await connect(page,'#/capabilities');await expect(page.getByText('0.27.0+local.1',{exact:true})).toBeVisible();await expect(page.locator('.field').filter({hasText:'真实 V31 DAG'})).toContainText('未接入');await page.setViewportSize({width:390,height:844});for(const hash of ['#/drafts','#/offline-science','#/capabilities']){await page.evaluate(h=>location.hash=h,hash);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}});
test('repair preview preserves method, saves local proposal and invalidates confirmation on change',async({page})=>{
 await connect(page,'#/screening');const option=page.getByLabel('项目／候选集合').locator('option').filter({hasText:'screening-fixtures'});test.skip(process.env.AUTOG_TEST_OPERATIONS!=='1','requires operations fixture');await expect(option).toHaveCount(1);await page.getByLabel('项目／候选集合').selectOption((await option.getAttribute('value'))!);await page.getByRole('link',{name:'打开计算详情'}).click();await page.getByRole('button',{name:'运行与诊断',exact:true}).click();await page.getByRole('button',{name:'读取报错与优化轨迹'}).click();await page.getByRole('button',{name:'生成修复草稿',exact:true}).click();const input='%mem=12GB\n# HF/STO-3G Opt Freq\n\nwater\n\n0 1\nO 0 0 0\nH 0 .7 .5\nH 0 -.7 .5\n\n';await page.getByLabel('原 Gaussian 输入',{exact:true}).setInputFiles({name:'water.gjf',mimeType:'text/plain',buffer:Buffer.from(input)});await expect(page.getByTestId('repair-diff')).toContainText('+ # HF/STO-3G Opt Freq SCF=(XQC,MaxCycle=512)');await page.getByLabel('修复理由').fill('查看 SCF 错误后形成提案');const c=page.getByLabel('我已确认原输入与诊断来源对应');await c.check();await page.getByRole('button',{name:'保存修复草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('修复草稿已保存');await page.getByLabel('MaxCycle',{exact:true}).fill('256');await expect(c).not.toBeChecked();
});
test('result export contains source and manual lineage remains explicitly unverified',async({page})=>{
 await connect(page,'#/analysis?tab=results');await page.locator('a[href^="#/archives/"]').first().click();await page.getByRole('button',{name:'补充来源备注',exact:true}).click();await page.getByLabel('父计算 / 输入版本引用').fill('manual-parent-example');await page.getByLabel('关联或修改理由').fill('人工补充来源，待独立核实');await page.getByRole('button',{name:'追加人工谱系记录'}).click();await expect(page.getByRole('status')).toContainText('原生父链和科学记录未改变');await page.keyboard.press('Escape');await page.getByRole('button',{name:'导出结果',exact:true}).click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'导出结果与来源 JSON'}).click();const stream=await (await dl).createReadStream();let raw='';for await(const b of stream!)raw+=b.toString();const data=JSON.parse(raw);expect(data.annotations[0].payload.binding).toBe('manual-unverified-reference');expect(data.detail.result.source.artifact.sha256).toMatch(/^[a-f0-9]{64}$/);
});
test('conflicting observed conditions block relative energy even when a user wants to compare',async({page})=>{
 const methods=new Map<string,string>();await page.route('**/api/archives/*/conditions',async route=>{const url=route.request().url();if(!methods.has(url))methods.set(url,methods.size===0?'HF':'B3LYP');const response=await route.fetch(),d=await response.json();const detail=await(await route.fetch({url:url.replace('/conditions','/details')})).json();d.observed={source:detail.result.source.artifact,steps:[{fields:{method:[{value:methods.get(url)}]}}]};await route.fulfill({json:d});});
 await connect(page,'#/screening');const option=page.getByLabel('项目／候选集合').locator('option').filter({hasText:'screening-fixtures'});test.skip(process.env.AUTOG_TEST_OPERATIONS!=='1','requires operations fixture');await expect(option).toHaveCount(1);await page.getByLabel('项目／候选集合').selectOption((await option.getAttribute('value'))!);await page.getByLabel('比较 screening-fixtures · candidate-0',{exact:true}).check();await page.getByLabel('比较 screening-fixtures · candidate-1',{exact:true}).check();await expect(page.locator('.comparison-panel')).toBeVisible();await page.getByLabel('人工可比性核对说明').fill('attempted comparison');await expect(page.locator('.comparison-panel tbody')).toContainText('冲突');await expect(page.getByLabel('我已核对结构身份、实际条件和结果来源')).toBeDisabled();
});
test('backup restores a valid revision chain in a separate browser and rejects edited content',async({page,browser})=>{
 await connect(page,'#/drafts');await fillDraft(page);await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存新草稿版本');await page.getByLabel('方法 / 泛函',{exact:true}).fill('B3LYP');await page.getByLabel('创建 / 修改理由').fill('second revision');await page.getByLabel('我已核对结构、立体化学、电荷').check();await page.getByRole('button',{name:'保存新版本',exact:true}).click();await expect.poll(()=>page.evaluate(()=>new Promise<number>((resolve,reject)=>{const r=indexedDB.open('autog-local-workbench-v1',1);r.onsuccess=()=>{const d=r.result,q=d.transaction('records').objectStore('records').count();q.onsuccess=()=>{resolve(q.result);d.close();};q.onerror=reject;};}))).toBe(2);await page.evaluate(()=>location.hash='#/calculations?tab=drafts');const promise=page.waitForEvent('download');await page.getByRole('button',{name:'导出全部浏览器笔记'}).click();const stream=await(await promise).createReadStream();let raw='';for await(const b of stream!)raw+=b.toString();const context=await browser.newContext();try{const other=await context.newPage();await other.goto('http://127.0.0.1:18765/#/calculations?tab=drafts');await other.getByLabel('只读访问令牌').fill(token);await other.getByRole('button',{name:'连接数据源'}).click();await other.getByLabel('恢复笔记包').setInputFiles({name:'notebook.json',mimeType:'application/json',buffer:Buffer.from(raw)});await expect(other.locator('.draft-shelf .task-card')).toHaveCount(2);const bad=JSON.parse(raw);bad.records[0].reason='tampered';await other.getByLabel('恢复笔记包').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await expect(other.getByRole('alert')).toContainText('记录摘要不匹配');await expect(other.locator('.draft-shelf .task-card')).toHaveCount(2);}finally{await context.close();}
});
