import {test,expect} from '@playwright/test';
const token='browser-test-only-'+'0'.repeat(32);
async function connect(page:any,hash='#/projects'){await page.goto('/'+hash);await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();}
test('project filters and page survive detail navigation and browser return',async({page})=>{
 await page.route('**/api/project-library',async route=>{const r=await route.fetch(),d=await r.json();const p=d.items.find((x:any)=>x.id==='gaussian-demo');d.items=Array.from({length:27},(_,i)=>({...p,id:i===12?'gaussian-demo':'project-'+i,label:'研究 '+i,states:['RUNNING']}));await route.fulfill({json:d});});
 await connect(page);await page.getByLabel('搜索项目',{exact:true}).fill('研究');await page.getByLabel('状态筛选').selectOption('RUNNING');await page.getByRole('button',{name:'下一页',exact:true}).click();await page.getByRole('link',{name:'研究 12 ↗',exact:true}).click();await expect(page.locator('.task')).toHaveCount(8);await page.getByRole('link',{name:'← 所有项目',exact:true}).click();await expect(page.getByLabel('搜索项目',{exact:true})).toHaveValue('研究');await expect(page.getByLabel('状态筛选')).toHaveValue('RUNNING');await expect(page.getByText('第 2 / 3 页')).toBeVisible();
});
test('selected result project and result filters survive opening an attempt',async({page})=>{
 await connect(page,'#/results');await page.getByLabel('结果项目').selectOption('gaussian-demo');await page.getByLabel('搜索计算结果',{exact:true}).fill('gaussian-normal');await expect(page.locator('tbody tr')).toHaveCount(1);await page.locator('tbody a').click();await page.getByRole('button',{name:'结构与结果',exact:true}).click();await expect(page.getByTestId('scientific-validation')).toBeVisible();await page.goBack();await expect(page.getByLabel('结果项目')).toHaveValue('gaussian-demo');await expect(page.getByLabel('搜索计算结果',{exact:true})).toHaveValue('gaussian-normal');await expect(page.locator('tbody tr')).toHaveCount(1);
});
test('failed result keeps step conditions, separate input declarations and source workflow',async({page})=>{
 test.skip(process.env.AUTOG_TEST_CONDITIONS!=='1');await connect(page);await page.getByRole('link',{name:'study-A ↗',exact:true}).click();await expect(page.locator('tbody .calc-unparsed')).toBeVisible();await page.locator('tbody a').click();const card=page.getByTestId('archive-conditions');await expect(card).toContainText('B3LYP');await expect(card).toContainText('(SMD,Solvent=Toluene)');await card.getByLabel('日志计算步骤').selectOption('1');await expect(card).toContainText('M06L');await expect(card.locator('.condition-overview')).not.toContainText('(SMD,Solvent=Toluene)');await card.getByText('输入文件声明 · 1 份', {exact:true}).click();await card.locator('.input-conditions details > summary').first().click();await expect(card).toContainText('输入与提交清单哈希匹配');await expect(card).toContainText('GenECP');await page.getByRole('button',{name:'运行与诊断',exact:true}).click();const evidence=page.getByTestId('historical-workflow');await expect(evidence).toContainText('提交意图');await expect(evidence).toContainText('提交脚本声明');await expect(evidence).toContainText('历史输入文件');await expect(evidence).toContainText('日志绑定未知');await expect(evidence).not.toContainText('提交回执');
});
