import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
const token='browser-test-only-'+'0'.repeat(32);
async function setup(page:Page){
 const headers={Authorization:'Bearer '+token};const library=await(await page.request.get('/api/project-library',{headers})).json();const source=library.items.find((g:any)=>g.label==='screening-fixtures');expect(source).toBeTruthy();const original=await(await page.request.get('/api/project-library/'+encodeURIComponent(source.id),{headers})).json();
 const entries=[original.items.slice(0,1),original.items.slice(0,2),original.items.slice(1,2)];const groups=['b5m12_0718m','b5m14_0719m','c4im3_0806'].map((label,i)=>({...source,id:'history-managed-'+i,label,count:entries[i].length,archive_ids:entries[i].map((a:any)=>a.archive_id)}));
 await page.route('**/api/project-library',r=>r.fulfill({json:{...library,items:groups}}));
 for(let i=0;i<groups.length;i++)await page.route('**/api/project-library/'+groups[i].id,r=>r.fulfill({json:{schema:'autog-project-library/1',project:groups[i],items:entries[i]}}));
 await page.goto('/#/projects');await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();return {groups,entries};
}
test('one b5 project owns its tasks; pin and rename persist and keep project links stable',async({page})=>{
 const {groups}=await setup(page);await expect(page.locator('.organized-card')).toHaveCount(2);const b5=page.locator('.organized-card').filter({has:page.getByRole('heading',{name:'b5 ↗',exact:true})});await expect(b5.locator('.organized-count')).toContainText('2 份结果');await b5.getByText('展开 2 个任务',{exact:true}).click();await expect(b5.locator('.member-row')).toHaveCount(2);
 const href=await b5.getByRole('link',{name:'查看项目全部结果'}).getAttribute('href');await b5.getByRole('link',{name:'查看项目全部结果'}).click();await expect(page.getByLabel('结果项目').locator('option')).toHaveCount(3);await expect(page.getByLabel('项目内任务').locator('option')).toHaveCount(3);await expect(page.locator('.science-index tbody tr')).toHaveCount(2);await page.getByLabel('项目内任务').selectOption(groups[0].id);await expect(page.getByLabel('结果项目').locator('option:checked')).toContainText('b5');await expect(page.getByLabel('项目内任务')).toHaveValue(groups[0].id);
 await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'项目',exact:true}).click();await b5.getByRole('button',{name:'置顶项目 b5',exact:true}).click();await page.getByLabel('排序',{exact:true}).selectOption('name-desc');await expect(page.locator('.organized-card').first()).toContainText('b5');await b5.locator('.organized-actions summary').click();await b5.locator('.organized-actions').getByLabel('展示项目名称',{exact:true}).fill('硼催化 b5');await b5.locator('.organized-actions').getByRole('button',{name:'保存整理',exact:true}).click();await expect(page.locator('.organized-card').first()).toContainText('硼催化 b5');
 await page.reload();await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();await expect(page.getByRole('button',{name:'取消置顶项目 硼催化 b5'})).toHaveAttribute('aria-pressed','true');await page.evaluate(h=>location.hash=h,href!);await expect(page.getByLabel('结果项目').locator('option:checked')).toContainText('硼催化 b5');await expect(page.locator('.science-index tbody tr')).toHaveCount(2);
});
test('comparison includes all b5 tasks and keeps checked results when adding another project',async({page})=>{
 const {entries}=await setup(page);const titles=entries.map(v=>v.at(-1).title);await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'分析',exact:true}).click();await page.getByRole('link',{name:'筛选与比较',exact:true}).click();await expect(page.getByLabel('项目／候选集合').locator('option').filter({hasText:'b5'})).toHaveCount(1);await expect(page.locator('.candidate-layout tbody tr')).toHaveCount(2);
 await page.getByLabel('比较 '+titles[0],{exact:true}).check();const other=page.getByLabel('项目／候选集合').locator('option').filter({hasText:'c4im3'});await page.getByLabel('项目／候选集合').selectOption((await other.getAttribute('value'))!);await expect(page.locator('.candidate-layout tbody tr')).toHaveCount(1);await expect(page.getByLabel('比较已选结果')).toContainText('已选 1 条结果');await page.getByLabel('比较 '+titles[2],{exact:true}).check();await expect(page.locator('.comparison-panel thead')).toContainText(titles[0]);await expect(page.locator('.comparison-panel thead')).toContainText(titles[2]);
 await page.locator('.screen-project-picker summary').click();await page.getByLabel('包含项目 b5',{exact:true}).check();await expect(page.locator('.candidate-layout tbody tr')).toHaveCount(2);await expect(page.getByLabel('比较 '+titles[0],{exact:true})).toBeChecked();await expect(page.getByLabel('比较 '+titles[2],{exact:true})).toBeChecked();
 await page.reload();await page.getByLabel('只读访问令牌').fill(token);await page.getByRole('button',{name:'连接数据源'}).click();await expect(page.locator('.candidate-layout tbody tr')).toHaveCount(2);await expect(page.getByLabel('比较已选结果')).toContainText('已选 2 条结果');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
