import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
const atom=(center:number,atomic_number:number,x:number,y:number,z:number)=>({center,atomic_number,x,y,z});
async function fixture(page:Page,corrupt='',delay=false){
 let packet:any;let release=()=>{};const gate=new Promise<void>(r=>{release=r;});
 await page.route('**/api/attempts/gaussian-normal/details',async route=>{const response=await route.fetch(),d=await response.json(),a=d.result.source.artifact;
 const g={units:'angstrom',orientation_kind:'standard-orientation',atoms:[atom(1,8,0,0,0),atom(2,1,1,0,0),atom(3,1,0,1,0)],source_span:{...a,start:10,end:20}};d.result.data.last_geometry=g;
 const vectors=[{center:1,atomic_number:8,dx:0,dy:0,dz:-.07},{center:2,atomic_number:1,dx:0,dy:.45,dz:.54},{center:3,atomic_number:1,dx:0,dy:-.45,dz:.54}];
 packet={schema:'auto-g16-mode-evidence/1',kind:'attempt',id:d.id,vibrations:{availability:'available',reason:null,source:{kind:'pinned-offline-vibration-modes',sha256:'b'.repeat(64),size_bytes:3000},data:{schema:'auto-g16-vibration-modes/1',kind:'attempt',id:d.id,decoder:{name:'autog-gaussian-cartesian-display-modes',version:'1.0.0'},vector_convention:'gaussian-printed-normalized-cartesian-displacements',result_source:d.result.source,reference_geometry:g,modes:d.result.data.frequencies_cm1.map((frequency:number,i:number)=>({mode_number:i+1,frequency_index:i,block_index:0,column_index:i,frequency_cm1:frequency,frequency_source_span:d.result.data.frequency_blocks[0].source_span,source_span:{...d.result.data.frequency_blocks[0].source_span,end:d.result.data.frequency_blocks[0].source_span.end+10},displacements:structuredClone(vectors)}))}}};
 d.review={availability:'available',reason:null,source:{kind:'historical-review-report'},data:{classification:'TEST_ONLY',acceptances:[],selected_final_geometry:g}};
 if(corrupt==='atom')packet.vibrations.data.modes[0].displacements[0].atomic_number=6;
 if(corrupt==='result')packet.vibrations.data.result_source={...packet.vibrations.data.result_source,result_id:'other'};
 if(corrupt==='geometry')packet.vibrations.data.reference_geometry={...g,atoms:[atom(1,8,1,1,1),...g.atoms.slice(1)]};
 if(corrupt==='frequency')packet.vibrations.data.modes[0].frequency_cm1=300;
 await route.fulfill({json:d});});
 await page.route('**/api/attempts/gaussian-normal/vibrations',async route=>{if(delay)await gate;await route.fulfill({json:packet}).catch(()=>{});});
 return release;
}
async function connect(page:Page){await page.goto('/#/attempts/gaussian-normal');await page.getByLabel('只读访问令牌').fill('browser-test-only-'+'0'.repeat(32));await page.getByRole('button',{name:'连接数据源'}).click();await page.getByRole('button',{name:'结构与结果',exact:true}).click();await expect(page.getByRole('button',{name:'读取振动模式'})).toBeVisible();}
test('real-shaped vectors animate, pause and restore reference geometry without changing measurements or connectivity',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page);await connect(page);const atom=page.locator('[data-testid="molecule-atom"][data-center="2"]');const baseline=await atom.getAttribute('transform');await page.locator('.structure-tools > summary').click();await page.getByLabel('测距原子 A').selectOption('2');await page.getByLabel('测距原子 B').selectOption('3');await expect(page.getByTestId('atom-distance')).toHaveText('1.4142 Å');
 await page.getByRole('button',{name:'读取振动模式'}).click();await page.getByRole('button',{name:'播放模式 1',exact:true}).click();await expect(page.getByTestId('vibration-controls')).toContainText('虚频方向示意');await expect(atom).not.toHaveAttribute('transform',baseline!);await expect(page.getByTestId('molecule-bond')).toHaveCount(2);await expect(page.getByTestId('atom-distance')).toHaveText('1.4142 Å');
 await page.getByRole('button',{name:'暂停动画',exact:true}).click();const paused=await atom.getAttribute('transform');await page.getByLabel('振动播放速度').fill('1.2');await expect(atom).toHaveAttribute('transform',paused!);await page.getByRole('button',{name:'回到参考结构',exact:true}).click();await expect(atom).toHaveAttribute('transform',baseline!);await page.getByRole('button',{name:'继续播放',exact:true}).click();await expect(atom).not.toHaveAttribute('transform',baseline!);await page.getByRole('button',{name:'关闭模式',exact:true}).click();await expect(page.getByTestId('vibration-controls')).toHaveCount(0);await expect(atom).toHaveAttribute('transform',baseline!);expect(errors).toEqual([]);
});
for(const bad of ['atom','result','geometry','frequency'])test(`mismatched mode ${bad} rejects playback`,async({page})=>{await fixture(page,bad);await connect(page);await page.getByRole('button',{name:'读取振动模式'}).click();await expect(page.getByText('模式读取失败或来源不一致，已禁止播放。')).toBeVisible();await expect(page.getByRole('button',{name:'播放模式 1',exact:true})).toHaveCount(0);});
test('Review source switches stop modes, missing mode sidecar remains unavailable',async({page})=>{
 await fixture(page);await connect(page);await page.getByRole('button',{name:'读取振动模式'}).click();await page.getByRole('button',{name:'播放模式 2',exact:true}).click();await page.getByLabel('结构来源').selectOption('review');await expect(page.getByTestId('vibration-controls')).toHaveCount(0);await page.getByRole('button',{name:'播放模式 3',exact:true}).click();await expect(page.getByLabel('结构来源')).toHaveValue('last');await expect(page.getByTestId('vibration-controls')).toContainText('模式 3');
 await page.unroute('**/api/attempts/gaussian-normal/vibrations');await page.reload();await page.getByLabel('只读访问令牌').fill('browser-test-only-'+'0'.repeat(32));await page.getByRole('button',{name:'连接数据源'}).click();await page.getByRole('button',{name:'结构与结果',exact:true}).click();await page.getByRole('button',{name:'读取振动模式'}).click();await expect(page.getByText('暂无绑定的振动位移数据，无法播放。')).toBeVisible();
});
test('mode controls fit mobile and pending responses cannot survive disconnect',async({page})=>{
 await fixture(page);await page.setViewportSize({width:390,height:844});await connect(page);await page.getByRole('button',{name:'读取振动模式'}).click();await page.getByRole('button',{name:'播放模式 1',exact:true}).click();await expect(page.getByTestId('vibration-controls')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'断开',exact:true}).click();await expect(page.getByTestId('molecule-scene')).toHaveCount(0);
 await page.unroute('**/api/attempts/gaussian-normal/details');await page.unroute('**/api/attempts/gaussian-normal/vibrations');const release=await fixture(page,'',true);try{await connect(page);await page.getByRole('button',{name:'读取振动模式'}).click();await expect(page.getByText('正在核对模式来源…')).toBeVisible();await page.getByRole('button',{name:'断开',exact:true}).click();release();await expect(page.getByTestId('vibration-controls')).toHaveCount(0);}finally{release();}
});
