import {populations} from './offline-science';
import {useEffect,useState} from 'react';
import {requestJSON} from './contract';
import {object} from './provenance';
import {isGeometry,MoleculeViewer} from './molecule-viewer';
import {download,csv} from './local-records';
import type {parseDetails} from './detail-panel';
type Detail=ReturnType<typeof parseDetails>;
export type ComparisonItem={id:string;kind:'archive'|'attempt';title:string;detail:Detail};
const identity=(i:ComparisonItem)=>i.kind+':'+i.id;
const labels:Record<string,string>={method:'方法',basis:'基组',environment:'环境',charge:'电荷',multiplicity:'多重度',dispersion:'色散',temperature_k:'温度 / K',pressure_atm:'压力 / atm'};
type Conditions=Record<string,string[]>;
function declared(d:Detail):Conditions{const c=d.context;const fields=object(c)&&object(c.conditions)&&object(c.conditions.declared)?c.conditions.declared:{};return Object.fromEntries(Object.keys(labels).map(k=>{const f=fields[k];return [k,object(f)&&f.availability==='available'&&['string','number'].includes(typeof f.value)?[String(f.value)]:[]];}));}
export function ComparisonPanel({items,token,metric}:{items:ComparisonItem[];token:string;metric:string}){
 const [temperature,setTemperature]=useState(''),[populationConfirmed,setPopulationConfirmed]=useState(false);
 const [conditions,setConditions]=useState<Record<string,Conditions>>({}),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[notes,setNotes]=useState('');const key=items.map(i=>identity(i)+JSON.stringify(i.detail.result.source)).join('|');
 useEffect(()=>{setConfirmed(false);setConditions({});setNotes('');setError('');if(items.length<2)return;const c=new AbortController();void (async()=>{const result:Record<string,Conditions>={};for(const item of items){let fields=declared(item.detail);if(item.kind==='archive')try{const v=await requestJSON(`/api/archives/${encodeURIComponent(item.id)}/conditions`,token,c.signal);if(!object(v)||v.schema!=='autog-conditions-view/1'||v.id!==item.id)throw Error();const observed=v.observed;if(object(observed)&&Array.isArray(observed.steps)){if(!object(observed.source)||!object(item.detail.result.source?.artifact)||observed.source.sha256!==item.detail.result.source.artifact.sha256)throw Error('condition-source-mismatch');// Multiple steps cannot be assigned to the displayed energy without a binding.
 if(observed.steps.length===1&&object(observed.steps[0])&&object(observed.steps[0].fields)){const fs=observed.steps[0].fields;fields=Object.fromEntries(Object.keys(labels).map(k=>[k,Array.isArray(fs[k])?[...new Set(fs[k].filter(object).map(x=>String(x.value)))]:[]]));}
 }}catch{if(!c.signal.aborted)setError('部分计算条件读取失败，保留为缺失。');}result[identity(item)]=fields;}if(!c.signal.aborted)setConditions(result);})();return()=>c.abort();},[key,token]);
 useEffect(()=>{setConfirmed(false);setPopulationConfirmed(false);},[metric]);
 useEffect(()=>setPopulationConfirmed(false),[key,confirmed,temperature]);
 const energy=(i:ComparisonItem)=>{const d=i.detail.result.data;if(!d)return null;const t=d.thermochemistry;const v=metric==='E'?d.final_energy_hartree:object(t)&&object(t.sum_electronic_gibbs_hartree)?t.sum_electronic_gibbs_hartree.value_hartree:null;return typeof v==='number'&&Number.isFinite(v)?v:null;};
 const value=(i:ComparisonItem,k:string)=>conditions[identity(i)]?.[k]??[];
 const keys=Object.keys(labels).filter(k=>metric==='G'||!['temperature_k','pressure_atm'].includes(k));
 const status=(k:string)=>{const values=items.map(i=>value(i,k));if(values.some(v=>v.length>1)||new Set(values.flat().map(x=>x.trim().toLowerCase())).size>1)return '冲突';return values.some(v=>v.length!==1)?'缺失':'记录一致';};
 const composition=(i:ComparisonItem)=>{const g=i.detail.result.data?.last_geometry;return isGeometry(g)?g.atoms.map(a=>a.atomic_number).sort((a,b)=>a-b).join(','):null;};
 const compatible=items.length>=2&&items.every(i=>energy(i)!==null&&composition(i)!==null&&composition(i)===composition(items[0]))&&keys.every(k=>status(k)!=='冲突')&&items.every(i=>conditions[identity(i)]);
 const minimum=compatible&&confirmed?Math.min(...items.map(i=>energy(i)!)):null;
 const populationAllowed=metric==='G'&&minimum!==null&&Number(temperature)>0&&Number(temperature)<=10000&&items.every(i=>value(i,'temperature_k').every(v=>Number.isFinite(Number(v))&&Math.abs(Number(v)-Number(temperature))<0.001));
 const weights=populationAllowed&&populationConfirmed?populations(items.map(i=>energy(i)!),Number(temperature)):[];
 const summary=()=>[['scope','selected set only; manually checked; not scientific acceptance'],['metric',metric],['reference','minimum energy of selected set'],['manual_notes',notes],[],['id','title','source_sha256',metric+'_hartree','delta_'+metric+'_kcal_mol',...keys,'imaginary_frequencies','execution_facts','selected_set_population','temperature_K'],...items.map(i=>{const d=i.detail.result.data;return [i.id,i.title,object(i.detail.result.source?.artifact)?i.detail.result.source?.artifact.sha256:'',energy(i),minimum===null?'':(energy(i)!-minimum)*627.509474,...keys.map(k=>value(i,k).join(' / ')||'missing'),Array.isArray(d?.frequencies_cm1)?d.frequencies_cm1.filter(f=>typeof f==='number'&&f<0).length:'unknown',JSON.stringify(d?.scientific_facts??null),weights[items.indexOf(i)]??'',weights.length?temperature:''];})];
 if(items.length<2)return null;
 return <section className="panel comparison-panel"><h2>选中结果的条件与结构比较</h2><p>日志只有一个步骤时显示该步条件；多步骤记录缺少能量绑定时保留未知。原生计划声明也需与实际结果核对。组成相同不能证明结构身份相同。</p>{error&&<p role="alert">{error}</p>}
 <div className="table-scroll"><table><thead><tr><th>比较项</th>{items.map(i=><th key={identity(i)}>{i.title}</th>)}<th>核对结果</th></tr></thead><tbody>{keys.map(k=><tr key={k}><th>{labels[k]}</th>{items.map(i=><td key={identity(i)}>{value(i,k).join(' / ')||'未记录 / 未绑定'}</td>)}<td>{status(k)}</td></tr>)}<tr><th>{metric} / Hartree</th>{items.map(i=><td key={identity(i)}>{energy(i)??'未记录'}</td>)}<td>原始值</td></tr><tr><th>Δ{metric} / kcal mol⁻¹</th>{items.map(i=><td key={identity(i)}>{minimum===null?'—':((energy(i)!-minimum)*627.509474).toFixed(3)}</td>)}<td>选中集合最低值为零</td></tr><tr><th>负频率 / cm⁻¹</th>{items.map(i=><td key={identity(i)}>{Array.isArray(i.detail.result.data?.frequencies_cm1)?i.detail.result.data.frequencies_cm1.filter(f=>typeof f==='number'&&f<0).join(', ')||'已读数组中无负频率':'未知'}</td>)}<td>需另查频率完整性</td></tr></tbody></table></div>
 <label>人工可比性核对说明（含缺失条件、温度和热化学处理）<textarea maxLength={2000} value={notes} onChange={e=>{setNotes(e.target.value);setConfirmed(false);}}/></label><label><input type="checkbox" checked={confirmed} disabled={!compatible||!notes.trim()} onChange={e=>setConfirmed(e.target.checked)}/>我已核对结构身份、实际条件和结果来源；在本次选中集合内显示相对能量。</label>{!compatible&&<p className="notice warning">条件有冲突、证据正在读取，或缺少相同组成/能量；暂不计算差值。</p>}
 {metric==='G'&&<section className="panel"><h3>选中集合的 Boltzmann 比例</h3><label>已核对的自由能计算温度 / K<input type="number" value={temperature} onChange={e=>setTemperature(e.target.value)}/></label><label><input type="checkbox" checked={populationConfirmed} disabled={!populationAllowed} onChange={e=>setPopulationConfirmed(e.target.checked)}/>温度与这些 G 的计算条件一致，且选中项为同体系、同电子态、已去重的可比较构象；仅对本集合归一化。</label>{weights.length>0&&<ul>{items.map((i,n)=><li key={identity(i)}>{i.title}：{(weights[n]*100).toFixed(3)}%</li>)}</ul>}<p className="micro">使用已保存的电子能 + Gibbs 校正，不替代 GoodVibes 的 qh-G，也不重新计算热化学。</p></section>}
 <div className="task-actions"><button onClick={()=>download('selected-comparison.csv',csv(summary()),'text/csv;charset=utf-8')}>导出比较表 CSV</button><button onClick={()=>download('selected-comparison.json',JSON.stringify({schema:'autog-selected-comparison/1',metric,reference:minimum,manual_confirmation:confirmed,population_temperature_k:weights.length?Number(temperature):null,populations:weights,population_confirmation:populationConfirmed,notes,conditions,items,scope:'selected-set-only; not reaction barrier or scientific acceptance'},null,2),'application/json')}>导出比较证据 JSON</button></div>
 <div className="compare-structures">{items.map(i=><section key={identity(i)}><h3>{i.title}</h3><MoleculeViewer last={i.detail.result.data?.last_geometry} review={null}/><details><summary>收敛与解析事实</summary><pre>{JSON.stringify(i.detail.result.data?.scientific_facts??{availability:'unavailable'},null,2)}</pre></details></section>)}</div></section>;
}
