import {useEffect,useState} from 'react';
import {requestJSON} from './contract';
import {artifact,boundSpan,SourceLocation} from './provenance';
import type {Artifact,SourceSpan,SourceTarget} from './provenance';
type Evidence={value:string|number;source_span:SourceSpan;line_start:number;line_end:number;evidence_kind:string;selectors?:string[];occurrence_count?:number};
type Step={index:number;route:Evidence;fields:Record<string,Evidence[]>;basis_blocks:Evidence[];ecp_blocks:Evidence[];diagnostics:string[]};
type Packet={schema:string;source:Artifact;steps:Step[];scope:string;extractor_version:string};
type View={schema:string;id:string;observed:Packet|null;declarations:{name:string;binding:string;submission_binding:string;conditions:Packet}[]};
const labels:Record<string,string>={method:'方法 / 泛函',basis:'基组',environment:'溶剂 / 环境',dispersion:'色散',charge:'电荷',multiplicity:'多重度',temperature_k:'温度 / K',pressure_atm:'压力 / atm'};
function valid(p:Packet):boolean{return !!p&&p.schema==='autog-calculation-conditions/1'&&p.extractor_version==='1.0.0'&&artifact(p.source)&&Array.isArray(p.steps)&&p.steps.every((s,i)=>s.index===i+1&&s.fields&&Object.keys(labels).every(k=>Array.isArray(s.fields[k]))&&Array.isArray(s.basis_blocks)&&Array.isArray(s.ecp_blocks)&&Array.isArray(s.diagnostics)&&[s.route,...Object.values(s.fields).flat(),...s.basis_blocks,...s.ecp_blocks].every(e=>e&&['string','number'].includes(typeof e.value)&&boundSpan(e.source_span,p.source)&&Number.isSafeInteger(e.line_start)&&Number.isSafeInteger(e.line_end)));}
function StepView({step:s,packet:p,onLocate,input=false}:{step:Step;packet:Packet;onLocate:(t:SourceTarget)=>void;input?:boolean}){
 const location=(e:Evidence,label:string)=>input?<small>输入第 {e.line_start}–{e.line_end} 行 · 字节 [{e.source_span.start}, {e.source_span.end})</small>:<><small>日志第 {e.line_start}–{e.line_end} 行</small><SourceLocation span={e.source_span} parent={p.source} label={`步骤 ${s.index} · ${label}`} onLocate={onLocate}/></>;
 return <div className="condition-step"><strong>步骤 {s.index}</strong><details><summary>完整计算关键词与来源</summary><pre>{s.route.value}</pre>{location(s.route,'计算关键词')}</details><dl className="condition-grid">{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{s.fields[key].length?s.fields[key].map((e,i)=><div key={i}><strong>{e.value==='Check'?'Check（继承条件，未展开）':e.value}</strong>{(e.occurrence_count??0)>1&&<small>日志重复记录 {e.occurrence_count} 次</small>}<small>{e.evidence_kind==='printed-standard-basis'?'程序打印基组':e.evidence_kind==='printed-route'?'日志关键词':'原文记录'}</small><details><summary>来源</summary>{location(e,label)}</details></div>):<span className="muted">未明确记录</span>}</dd></div>)}</dl>{(['basis_blocks','ecp_blocks'] as const).map(key=><details key={key}><summary>{key==='basis_blocks'?'逐元素 / 中心基组':'ECP'} · {s[key].length} 个原文块</summary>{s[key].length?s[key].map((e,i)=><div key={i}><strong>{e.selectors?.join(' · ')}</strong><pre>{e.value}</pre>{location(e,key==='basis_blocks'?'基组卡片':'ECP 卡片')}</div>):<p>未提取到可独立确认的逐元素块；不据此推断统一基组或无 ECP。</p>}</details>)}{s.diagnostics.length>0&&<details><summary>提取范围说明</summary><pre>{s.diagnostics.join('\n')}</pre></details>}</div>;
}
function ConditionOverview({step:s}:{step:Step}){
 return <dl className="condition-overview">{Object.entries(labels).map(([key,label])=>{const values=[...new Set(s.fields[key].map(e=>String(e.value)))];return <div key={key}><dt>{label}</dt><dd>{values.length?values.map((v,i)=><span key={i}>{v==='Check'?'Check（继承未展开）':v}{i<values.length-1?' / ':''}</span>):'未明确记录'}</dd></div>;})}</dl>;
}
export function ConditionsPanel({id,token,onLocate}:{id:string;token:string;onLocate:(t:SourceTarget)=>void}){
 const [data,setData]=useState<View|null>(null),[error,setError]=useState(false),[step,setStep]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setError(false);setStep(0);requestJSON(`/api/archives/${encodeURIComponent(id)}/conditions`,token,c.signal).then(v=>{const d=v as View;if(d.schema!=='autog-conditions-view/1'||d.id!==id||d.observed!==null&&(!valid(d.observed)||d.observed.scope!=='log-observation')||!Array.isArray(d.declarations)||!d.declarations.every(x=>x.binding==='input-declaration-log-binding-unknown'&&typeof x.name==='string'&&['sha256-verified','unverified-source-file'].includes(x.submission_binding)&&valid(x.conditions)&&x.conditions.scope==='input-declaration'))throw Error();if(!c.signal.aborted)setData(d);}).catch(()=>{if(!c.signal.aborted)setError(true);});return()=>c.abort();},[id,token]);
 return <section className="archive-conditions" data-testid="archive-conditions"><div className="conditions-heading"><h3>计算条件 <small>日志记录 · 按步骤</small></h3>{!!data?.observed?.steps.length&&<label>日志计算步骤<select aria-label="日志计算步骤" value={step} onChange={e=>setStep(Number(e.target.value))}>{data.observed.steps.map((s,i)=><option key={i} value={i}>步骤 {s.index} · {String(s.route.value).slice(0,110)}</option>)}</select></label>}</div>{error?<p role="alert">计算条件来源校验失败。</p>:!data?<p>读取计算条件…</p>:<>{data.observed?.steps.length?<><ConditionOverview step={data.observed.steps[step]}/><details className="condition-evidence"><summary>计算关键词、逐字段来源与混合基组 / ECP</summary><p className="micro muted">逐步骤显示原文，与输入声明分开；未记录的条件不从前一步或默认值补齐。</p><StepView step={data.observed.steps[step]} packet={data.observed} onLocate={onLocate}/></details></>:<p>此文件尚无合格的计算条件记录。</p>}<details className="input-conditions"><summary>输入文件声明 · {data.declarations.length} 份</summary><p>以下输入来自同目录文件或已核对的历史提交清单。输入与当前日志、步骤之间尚未建立验证关系，不自动合并为同一套条件。</p>{data.declarations.map((d,i)=><details key={i}><summary>{d.name}</summary><p>{d.submission_binding==='sha256-verified'?'输入与提交清单哈希匹配':'同目录输入候选，未核实提交关系'}</p><code>SHA-256 {d.conditions.source.sha256}</code>{d.conditions.steps.map(s=><StepView key={s.index} step={s} packet={d.conditions} onLocate={onLocate} input/>)}</details>)}</details></>}</section>;
}
