import {useEffect,useState} from 'react';
import {records,verifyRecord,importRecords,download,localFile,sha256} from './local-records';
import type {LocalRecord} from './local-records';
import {routeLink} from './navigation';
export function DraftShelf(){
 const [items,setItems]=useState<LocalRecord[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const refresh=()=>records().then(rs=>{setItems(rs);setLoaded(true);}).catch(e=>{setError(e.message);setLoaded(true);});useEffect(()=>{void refresh();},[]);
 async function restore(file?:File){if(!file)return;try{const f=await localFile(file,16*1024*1024),b=JSON.parse(f.text);if(b.schema!=='autog-local-notebook/1')throw Error('需要本工作台导出的笔记包。');await importRecords(b.records);await refresh();setError('');}catch(e){setError((e as Error).message);}}
 async function exportInput(r:LocalRecord){try{await verifyRecord(r);if(typeof r.payload.input!=='string'||await sha256(r.payload.input)!==r.payload.input_sha256)throw Error('草稿输入摘要不匹配。');download('draft-'+r.id+'.gjf',r.payload.input);}catch(e){setError((e as Error).message);}}
 return <><div className="task-actions"><button onClick={()=>download('workbench-notebook.json',JSON.stringify({schema:'autog-local-notebook/1',records:items},null,2),'application/json')}>导出全部浏览器笔记</button><label>恢复笔记包<input type="file" accept=".json" onChange={e=>void restore(e.target.files?.[0])}/></label></div><p className="micro">浏览器草稿保存在当前地址和浏览器中，请备份；服务端草稿保存在本地任务库中。两个来源分别保留原有版本与身份。</p>{error&&<p role="alert">{error}</p>}{!loaded&&<p role="status">读取浏览器草稿…</p>}<div className="draft-shelf">{items.filter(r=>r.kind==='draft').reverse().map(r=>{const f=r.payload.form as {title?:string}|undefined,src=r.payload.evidence_source as {kind?:string;id?:string}|undefined;return <article className="task-card" key={r.id}><span className="draft-origin">当前浏览器 · {f?'输入草稿':'修复草稿'}</span><h3>{f?.title??String(r.payload.title??'草稿')}</h3><p>{r.created_at} · {r.reason}</p>{typeof r.payload.project_context==='string'&&r.payload.project_context&&<p>项目浏览归属：{r.payload.project_context}</p>}<small>父版本：{r.parent??'无'}</small><div className="task-actions">{f&&<a href={routeLink('#/calculations',{tab:'new',record:r.id,project:typeof r.payload.project_context==='string'?r.payload.project_context:undefined})}>继续编辑此版本</a>}<button onClick={()=>void exportInput(r)}>导出输入</button>{src?.id&&['archive','attempt'].includes(src.kind??'')&&<a href={'#/'+(src.kind==='archive'?'archives':'attempts')+'/'+encodeURIComponent(src.id)}>返回来源结果</a>}</div><details><summary>版本记录</summary><pre>{JSON.stringify(r,null,2)}</pre></details></article>;})}</div>{loaded&&!items.some(r=>r.kind==='draft')&&<p>当前浏览器暂无草稿。</p>}</>;
}
