import {routeLink,useSessionValue} from './navigation';
import {useEffect,useState} from 'react';
import {MoleculeViewer,isGeometry} from './molecule-viewer';
import type {Geometry} from './molecule-viewer';
import {emptyForm,buildInput,parseStructure,lineDiff,routePatch} from './draft-model';
import type {DraftForm} from './draft-model';
import {appendRecord,records,verifyRecord,importRecords,localFile,sha256,download,xyz} from './local-records';
import type {LocalRecord,SourceRef} from './local-records';
const textFields: [keyof DraftForm,string,string][]=[['title','计算标题','例如 molecule-opt'],['method','方法 / 泛函','例如 B3LYP'],['basis','基组','例如 6-31G(d)'],['environment','环境','gas 或 SCRF=(SMD,Solvent=Water)'],['charge','总电荷','整数'],['multiplicity','自旋多重度','正整数'],['cores','CPU 核数','1–512'],['memory','内存 / GiB','1–4096'],['walltime','Walltime','24:00:00'],['extra','附加关键词（可选）','例如 SCF=(XQC,MaxCycle=512)']];
export function DraftPanel({recordId,project=''}:{recordId?:string;project?:string}){
 const cache='autog-unsaved-draft:'+project+':'+(recordId??'new');
 const [form,setForm]=useSessionValue<DraftForm>(cache+':form',{...emptyForm}),[geometry,setGeometry]=useSessionValue<Geometry|null>(cache+':geometry',null),[source,setSource]=useSessionValue<SourceRef|null>(cache+':source',null),[warning,setWarning]=useState<string[]>([]),[originalRoute,setOriginalRoute]=useState(''),[reviewed,setReviewed]=useState(false),[reason,setReason]=useSessionValue(cache+':reason',''),[saved,setSaved]=useState<LocalRecord[]>([]),[parent,setParent]=useSessionValue<LocalRecord|null>(cache+':parent',null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>records().then(setSaved).catch(e=>setError(String(e.message)));useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(!recordId)return;if(geometry&&source)return;void records().then(rs=>{const r=rs.find(r=>r.id===recordId);if(r)void restore(r);else setError('未找到这条浏览器草稿，请核对浏览器与工作台地址。');}).catch(e=>setError(e.message));},[recordId]);
 let input='',validation='';try{if(geometry)input=buildInput(form,geometry);else validation='请先导入结构。';}catch(e){validation=(e as Error).message;}
 const changed=()=>{setReviewed(false);setMessage('');};
 async function structure(file?:File){if(!file)return;setError('');changed();try{const f=await localFile(file,2*1024*1024),p=parseStructure(f.text,file.name);setGeometry(p.geometry);setSource(f.source);setWarning(p.warnings);setOriginalRoute(p.route??'');setParent(null);setForm({...emptyForm,title:file.name.replace(/\.[^.]+$/,''),charge:p.charge===undefined?'':String(p.charge),multiplicity:p.multiplicity===undefined?'':String(p.multiplicity)});}catch(e){setGeometry(null);setSource(null);setError((e as Error).message);}}
 async function save(){if(!geometry||!input||!source||!reviewed||busy)return;setBusy(true);setError('');try{const r=await appendRecord('draft',{form,geometry,source,input,input_sha256:await sha256(input),authority:'local-draft-only',project_context:project},reason,parent?.id??null);setParent(r);setMessage('已保存新草稿版本；未创建审批或提交任务。');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function restore(r:LocalRecord){try{await verifyRecord(r);const p=r.payload;if(r.kind!=='draft'||!isGeometry(p.geometry)||!p.form||typeof p.form!=='object'||!p.source||typeof p.source!=='object'||typeof p.input!=='string'||await sha256(p.input)!==p.input_sha256||buildInput(p.form as DraftForm,p.geometry)!==p.input)throw Error('这条记录不是本向导生成的有效草稿。');setForm(p.form as DraftForm);setGeometry(p.geometry);setSource(p.source as SourceRef);setParent(r);setReason('');setError('');setWarning([]);setOriginalRoute('');changed();}catch(e){setError((e as Error).message);}}
 async function restoreFile(file?:File){if(!file)return;setError('');try{const {text}=await localFile(file,16*1024*1024);const bundle=JSON.parse(text);if(bundle.schema!=='autog-local-notebook/1')throw Error('需要本工作台导出的笔记包。');await importRecords(bundle.records);await refresh();setMessage('笔记包已校验并合并，未覆盖已有版本。');}catch(e){setError((e as Error).message);}}
 return <><div className="page-heading"><div className="eyebrow">CALCULATION DRAFT</div><h1>新计算草稿</h1><p>导入结构、明确计算条件，检查输入后保存独立版本。</p></div>
 <p className="notice">草稿保存在当前浏览器、当前工作台地址的本地库中。换浏览器或清除网站数据会丢失本地记录，请导出笔记包备份。这里不创建 CalculationPlan 审批或执行快照。</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message} <a href="#/calculations?tab=drafts">查看草稿列表 →</a></p>}
 <section className="panel"><h2>1 · 结构与条件</h2><label>导入结构文件<input type="file" accept=".xyz,.gjf,.com,.sdf,.mol" onChange={e=>void structure(e.target.files?.[0])}/></label>{source&&<p>{source.name} · SHA-256 <code>{source.sha256}</code></p>}{warning.map(w=><p className="notice warning" key={w}>{w}</p>)}{originalRoute&&<details><summary>原输入关键词（仅参考）</summary><pre>{originalRoute}</pre></details>}
 <div className="draft-fields"><label>计算类型<select value={form.job} onChange={e=>{setForm({...form,job:e.target.value as DraftForm['job']});changed();}}><option value="optfreq">优化 + 频率</option><option value="opt">几何优化</option><option value="sp">单点能</option></select></label>{textFields.map(([key,label,placeholder])=><label key={key}>{label}<input value={form[key]} placeholder={placeholder} onChange={e=>{setForm({...form,[key]:e.target.value});changed();}}/></label>)}</div>
 <p className="micro">Walltime 仅作为草稿资源声明保存；Gaussian 输入不包含调度器脚本。电子数检查不能代替电子态与立体化学审核。</p>{geometry&&<MoleculeViewer last={geometry} review={null} frameLabel="导入结构"/>}</section>
 <section className="panel"><h2>2 · 输入预览与版本</h2>{validation?<p role="status">{validation}</p>:<pre data-testid="draft-input">{input}</pre>}{parent&&<><p>父版本：<code>{parent.id}</code> · {parent.created_at}</p><details><summary>与父版本对比</summary><pre>{lineDiff(String(parent.payload.input??''),input)}</pre></details></>}
 <label>创建 / 修改理由<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={!input}/>我已核对结构、立体化学、电荷、多重度、方法、环境与资源；保存为待审核草稿。</label>
 <div className="task-actions"><button disabled={!input||!reviewed||!reason.trim()||busy} onClick={()=>void save()}>保存新版本</button><button disabled={!input||!reviewed} onClick={()=>download(form.title+'.gjf',input)}>导出 Gaussian 输入</button><button disabled={!geometry} onClick={()=>geometry&&download(form.title+'.xyz',xyz(geometry,form.title))}>导出 XYZ</button></div></section>
 <p><a href={routeLink('#/calculations',{tab:'drafts'})}>返回统一草稿列表与备份 →</a></p></>;
}

export function RepairPanel({source,geometry}:{source?:SourceRef;geometry?:Geometry}){
 const [original,setOriginal]=useState(''),[fileSource,setFileSource]=useState<SourceRef|null>(null),[mode,setMode]=useState<'scf'|'opt'>('scf'),[cycles,setCycles]=useState('512'),[reuse,setReuse]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[parent,setParent]=useState<LocalRecord|null>(null),[busy,setBusy]=useState(false);
 const reset=()=>{setConfirmed(false);setMessage('');};let revised='',failure='';
 try{if(original){revised=routePatch(original,mode,Number(cycles));if(reuse){if(!geometry)throw Error('缺少已绑定几何。');const parsed=parseStructure(original,'repair.gjf');if(parsed.geometry.atoms.map(a=>a.atomic_number).join(',')!==geometry.atoms.map(a=>a.atomic_number).join(','))throw Error('输入与结果的原子序列不同，不能替换坐标。');const block=/((?:^|\n)[ \t]*-?\d+[ \t]+\d+[ \t]*\r?\n)((?:[^\r\n]+\r?\n)+)/;if(!block.test(revised))throw Error('坐标边界不明确。');revised=revised.replace(block,(_all,cm)=>cm+xyz(geometry).split('\n').slice(2).join('\n'));}}}catch(e){failure=(e as Error).message;}
 async function load(file?:File){if(!file)return;reset();setParent(null);try{const f=await localFile(file,2*1024*1024);parseStructure(f.text,file.name);setOriginal(f.text);setFileSource(f.source);setError('');}catch(e){setOriginal('');setError((e as Error).message);}}
 async function save(){if(!revised||failure||!confirmed||busy)return;setBusy(true);try{const r=await appendRecord('draft',{title:'修复预览 · '+fileSource?.name,input:revised,input_sha256:await sha256(revised),original_input:original,input_source:fileSource,evidence_source:source??null,reuse_geometry:reuse,geometry:reuse?geometry:null,recipe:{mode,cycles:Number(cycles)},authority:'local-repair-proposal-only'},reason,parent?.id??null);setParent(r);setMessage('修复草稿已保存，可在计算 → 草稿中查看、导出输入和备份。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>修复输入预览</h2><p>导入对应原输入；保留方法和基组，显示关键词或坐标的明确修改。采集不完整、解析失败应先补齐证据，不直接重算。</p>{source&&<p>诊断来源：{source.name} · <code>{source.sha256}</code></p>}
 <label>原 Gaussian 输入<input type="file" accept=".gjf,.com" onChange={e=>void load(e.target.files?.[0])}/></label><div className="draft-fields"><label>修改方案<select value={mode} onChange={e=>{setMode(e.target.value as 'scf'|'opt');reset();}}><option value="scf">SCF 改用 XQC 并设置 MaxCycle</option><option value="opt">调整 Opt MaxCycle</option></select></label><label>MaxCycle<input type="number" min="1" max="10000" value={cycles} onChange={e=>{setCycles(e.target.value);reset();}}/></label></div>
 {geometry&&<label><input type="checkbox" checked={reuse} onChange={e=>{setReuse(e.target.checked);reset();}}/>改用此日志中所选完整优化段的最后结构（需核对该分段与输入对应）</label>}
 {(error||failure)&&<p role="alert">{error||failure}</p>}{original&&!failure&&<pre data-testid="repair-diff">{lineDiff(original,revised)}</pre>}
 <label>修复理由<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={!revised||!!failure}/>我已确认原输入与诊断来源对应，并检查所有差异。此记录仅是修复提案。</label><div className="task-actions"><button disabled={!confirmed||!reason.trim()||busy} onClick={()=>void save()}>保存修复草稿</button><button disabled={!confirmed||!revised||!!failure} onClick={()=>download('repair-preview.gjf',revised)}>导出修复输入</button></div>{message&&<p role="status">{message} <a href="#/calculations?tab=drafts">查看草稿列表 →</a></p>}</section>;
}
