import {useEffect,useState} from 'react';
import {requestJSON} from './contract';
type Status={schema:string;configured:boolean;root:string;incoming:string;auto_archive:boolean;jobs:{id:string;state:string;updated_at:string;error:string|null}[]};
function check(v:unknown):Status{const s=v as Status;if(!s||s.schema!=='autog-local-library/1'||typeof s.configured!=='boolean'||typeof s.root!=='string'||typeof s.incoming!=='string'||typeof s.auto_archive!=='boolean'||!Array.isArray(s.jobs)||!s.jobs.every(j=>typeof j.id==='string'&&typeof j.state==='string'&&typeof j.updated_at==='string'&&(j.error===null||typeof j.error==='string')))throw Error('contract');return s;}
export function LibraryPanel({token}:{token:string}){
 const [data,setData]=useState<Status|null>(null),[root,setRoot]=useState(''),[auto,setAuto]=useState(true),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const c=new AbortController();const load=()=>requestJSON('/api/library',token,c.signal).then(v=>{const s=check(v);setData(s);}).catch(()=>{if(!c.signal.aborted)setError('本地库未启用或无法读取。');});void load();const t=setInterval(load,5000);return()=>{c.abort();clearInterval(t);};},[token]);
 useEffect(()=>{if(data){setRoot(data.root);setAuto(data.auto_archive);}},[data?.root,data?.auto_archive]);
 async function action(name:string,body:object){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/library/'+name,{method:'POST',headers:{'Content-Type':'application/json','X-Autog-Library':'library/1',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),credentials:'omit',redirect:'error'});if(!r.ok)throw Error();const v=await r.json();if(name!=='capture')setData(check(v));setMessage(name==='capture'?'完整回收回执已保存。开启自动归档后会处理；归档完成后刷新结果页。':'已保存。');}catch{setError('操作未完成：请检查绝对路径、文件完整性及本地库状态。原计算不会重新执行。');}finally{setBusy(false);}}
 return <><div className="page-heading"><h1>本地库设置</h1><p>保存、核验和归档本地回收结果；原始计算结果保持只读。</p></div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{data&&<><section className="panel"><h2>统一保存路径</h2><form onSubmit={e=>{e.preventDefault();void action('settings',{root,auto_archive:auto});}}><label>本地库绝对路径<input aria-label="本地库绝对路径" value={root} onChange={e=>setRoot(e.target.value)} required placeholder="/Users/你的用户名/Documents/Auto-Gaussian-Data"/></label><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> 工作台运行时自动处理完整回收回执</label><button disabled={busy} type="submit">保存本地库设置</button></form><p>回收入口：<code>{data.incoming||'设置后生成'}</code></p><p className="muted">归档保存日志、输入和小型来源文件，按内容哈希去重。大型 .chk 检查点仍需单独备份。</p></section>
 <section className="panel"><h2>接入已经回收的结果</h2><p>上游回收流程应在传输成功后调用本地完成回执接口。已有文件也可以从这里接入。</p><form onSubmit={e=>{e.preventDefault();if(confirmed)void action('capture',{source});}}><label>已完成回收的文件夹<input aria-label="已完成回收的文件夹" value={source} onChange={e=>{setSource(e.target.value);setConfirmed(false);}} required/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 文件传输已结束，目录内容已完整</label><button disabled={busy||!confirmed||!data.configured||!data.auto_archive}>核验并归档本地文件</button></form><p className="muted">不会连接服务器或提交计算。后台归档失败后可独立重试。</p></section>
 <section className="panel"><h2>归档队列 · 最近 50 项</h2>{!data.jobs.length?<p>暂无回收回执。</p>:<table><thead><tr><th>回收批次</th><th>状态</th><th>更新时间</th><th>归档处理</th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id}><td title={j.id}><code>{j.id.slice(0,16)}</code></td><td>{{archived:'已入库',failed:'归档失败',queued:'等待归档',importing:'正在归档'}[j.state]??j.state}</td><td>{j.updated_at}</td><td>{j.error&&<p>{j.error}</p>}{j.state==='failed'&&<button disabled={busy} onClick={()=>void action('retry',{id:j.id})}>仅重试归档</button>}</td></tr>)}</tbody></table>}</section></>}</>;
}
