import {parseSelection} from './result-selection';
import {routeParams,routeLink} from './navigation';
import {useState} from 'react';
import {MoleculeViewer} from './molecule-viewer';
import {parseIRC,parseGoodVibes,populations} from './offline-science';
import type {IRCData,ThermoTable} from './offline-science';
import {localFile,download,csv,xyz,exportSVG} from './local-records';
import type {SourceRef} from './local-records';
const template={schema:'autog-irc-trajectory/1',coordinate_units:'point-index',scope:'synthetic format example, not a scientific result',points:[0,1].map(point=>({branch:'forward',point,coordinate:point,energy_hartree:-1-point*.01,geometry:{units:'angstrom',atoms:[{center:1,atomic_number:1,x:0,y:0,z:0},{center:2,atomic_number:1,x:0,y:0,z:.74+point*.1}]}}))};
export function OfflineSciencePanel({tool='irc'}:{tool?:'irc'|'thermo'}){
 const selectedResults=parseSelection(routeParams().get('selection'));
 const [irc,setIRC]=useState<IRCData|null>(null),[ircSource,setIRCSource]=useState<SourceRef|null>(null),[step,setStep]=useState(0),[table,setTable]=useState<ThermoTable|null>(null),[thermoSource,setThermoSource]=useState<SourceRef|null>(null),[column,setColumn]=useState(''),[selected,setSelected]=useState<string[]>([]),[temp,setTemp]=useState(''),[context,setContext]=useState(''),[confirmed,setConfirmed]=useState(false),[ircError,setIRCError]=useState(''),[thermoError,setThermoError]=useState('');
 async function loadIRC(file?:File){if(!file)return;setIRC(null);setIRCSource(null);setIRCError('');try{const f=await localFile(file,32*1024*1024);setIRC(parseIRC(f.text,file.name));setIRCSource(f.source);setStep(0);}catch(e){setIRCError((e as Error).message);}}
 async function loadThermo(file?:File){if(!file)return;setTable(null);setThermoSource(null);setThermoError('');setSelected([]);setConfirmed(false);setTemp('');setContext('');try{const f=await localFile(file);const t=parseGoodVibes(f.text);setTable(t);setThermoSource(f.source);setColumn(t.columns.find(c=>/^qh-G\(T\)/.test(c))!);}catch(e){setThermoError((e as Error).message);}}
 const point=irc?.points[step];const coordinates=irc?.points.map(p=>(p.branch==='reverse'?-1:1)*p.coordinate)??[],energies=irc?.points.map(p=>p.energy_hartree)??[],minX=Math.min(...coordinates),rangeX=Math.max(...coordinates)-minX||1,minE=Math.min(...energies),rangeE=Math.max(...energies)-minE||1;const xy=(i:number)=>[80+(coordinates[i]-minX)/rangeX*620,180-(energies[i]-minE)/rangeE*135];
 const chosen=table?.rows.filter(r=>selected.includes(r.name))??[];let pops:number[]=[];if(confirmed)try{pops=populations(chosen.map(r=>r.values[column]),Number(temp));}catch{/* Inputs gate confirmation below. */}
 const canPopulation=chosen.length>=2&&Number(temp)>0&&Number(temp)<=10000&&context.trim().length>0&&/^(?:qh-)?G\(T\)(?:_SPC)?$/.test(column);
 return <><div className="page-heading"><div className="eyebrow">OFFLINE SCIENCE</div><h1>{tool==='irc'?'IRC 轨迹分析':'热化学与构象比例'}</h1><p>本地文件在浏览器中读取，不上传、不运行计算或重新执行 GoodVibes。</p></div>
 {selectedResults.length>0&&<section className="panel analysis-selection"><div><strong>已承接 {selectedResults.length} 条结果</strong><p>{selectedResults.map(r=>r.title).join(' · ')}</p><small>导入文件需自行核对与上述结果的对应关系；不会按名称猜测绑定。</small></div><a href={routeLink('#/analysis',{tab:'compare',selection:JSON.stringify(selectedResults),project:routeParams().get('project')??undefined})}>用选中结果比较能量与比例 →</a></section>}
 <section hidden={tool!=='irc'} className="panel"><h2>IRC 曲线与逐点结构</h2><p>接受带显式分支、能量和坐标单位的 JSON 或多帧 XYZ。请从已核对的 IRC 来源导出此格式；普通优化日志不能当作 IRC。导入只确认格式，不证明双向终止或端点身份。</p><div className="task-actions"><label>导入 IRC 轨迹<input type="file" accept=".json,.xyz" onChange={e=>void loadIRC(e.target.files?.[0])}/></label><button onClick={()=>download('irc-format-example.json',JSON.stringify(template,null,2),'application/json')}>下载格式示例</button></div><details><summary>多帧 XYZ 注释格式</summary><pre>irc=forward point=0 coordinate=0 energy_hartree=-100.123 units=point-index</pre><p>每帧的原子数和顺序一致；分支内点号连续、坐标递增。reverse 分支在图上取负横坐标，仅表示分支方向。</p></details>{ircError&&<p role="alert">{ircError}</p>}
 {irc&&point&&<><p>{ircSource?.name} · SHA-256 <code>{ircSource?.sha256}</code></p><p>{irc.scope??'来源科学范围未声明'} · 已导入 {irc.points.length} 点 · 正向 {irc.points.filter(p=>p.branch==='forward').length} / 反向 {irc.points.filter(p=>p.branch==='reverse').length}</p>
 <svg className="optimization-plot irc-plot" viewBox="0 0 760 230" role="img" aria-label="IRC 能量曲线"><text x="10" y="20">E / Hartree</text><text x="0" y="43" fontSize="9">{Math.max(...energies).toFixed(6)}</text><text x="0" y="180" fontSize="9">{minE.toFixed(6)}</text><path d="M80 35V185H715" fill="none" stroke="#667"/>{(['forward','reverse'] as const).map(b=><polyline key={b} fill="none" stroke={b==='forward'?'#702879':'#267a9e'} strokeWidth="2" points={irc.points.flatMap((p,i)=>p.branch===b?[xy(i).join(',')]:[]).join(' ')}/>)}{irc.points.map((p,i)=><circle key={p.branch+p.point} cx={xy(i)[0]} cy={xy(i)[1]} r={step===i?6:4} fill={step===i?'#d77814':'#702879'} role="button" tabIndex={0} aria-label={`IRC ${p.branch} 点 ${p.point}`} onClick={()=>setStep(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setStep(i);}}}/>)}<text x="80" y="207">{minX.toPrecision(4)}</text><text x="630" y="207">{Math.max(...coordinates).toPrecision(4)}</text><text x="240" y="225">坐标 / {irc.coordinate_units}</text></svg>
 <label>IRC 点<select value={step} onChange={e=>setStep(Number(e.target.value))}>{irc.points.map((p,i)=><option key={i} value={i}>{p.branch} · {p.point} · {p.energy_hartree} Eh</option>)}</select></label><p>当前点：{point.branch} / {point.point} · E={point.energy_hartree} Hartree · 坐标={point.coordinate}</p><MoleculeViewer last={point.geometry} review={null} frameLabel="当前 IRC 点结构"/><p>端点人工标签：forward={irc.endpoints?.forward??'未识别'}；reverse={irc.endpoints?.reverse??'未识别'}。标签本身不是端点验证。</p><div className="task-actions"><button onClick={()=>download('irc-selected.xyz',xyz(point.geometry,`${point.branch} ${point.point} source ${ircSource?.sha256}`))}>导出选中点 XYZ</button><button onClick={e=>{const svg=e.currentTarget.closest('section')?.querySelector('svg.irc-plot');if(svg)exportSVG(svg,'irc.svg');}}>导出 IRC 图 SVG</button><button onClick={()=>download('irc-points.csv',csv([['branch','point','coordinate','coordinate_units','energy_hartree','source_sha256'],...irc.points.map(p=>[p.branch,p.point,p.coordinate,irc.coordinate_units,p.energy_hartree,ircSource?.sha256])]),'text/csv;charset=utf-8')}>导出轨迹表</button></div></>}
 </section>
 <section hidden={tool!=='thermo'} className="panel"><h2>GoodVibes 表与构象比例</h2><p>导入一个条件下的 GoodVibes 文本表或逗号分隔表，保留 E、G(T)、qh-G(T) 等实际列。能量按 GoodVibes 表的 Hartree 单位解释。温度和处理条件必须从原计算核对，不能用新温度重新解释已有 G。</p><label>导入 GoodVibes 结果<input type="file" accept=".txt,.dat,.out,.csv" onChange={e=>void loadThermo(e.target.files?.[0])}/></label>{thermoError&&<p role="alert">{thermoError}</p>}
 {table&&<><p>{thermoSource?.name} · SHA-256 <code>{thermoSource?.sha256}</code></p><details><summary>原表前文与计算条件</summary><pre>{table.preamble||'文件没有前文；请另行核对。'}</pre></details><div className="draft-fields"><label>自由能列<select value={column} onChange={e=>{setColumn(e.target.value);setConfirmed(false);}}>{table.columns.map(c=><option key={c}>{c}</option>)}</select></label><label>该表计算温度 / K<input type="number" value={temp} onChange={e=>{setTemp(e.target.value);setConfirmed(false);}}/></label></div><label>核对说明：组成、电子态、方法、溶剂、标准态、频率校正、去重及所选集合<textarea value={context} maxLength={3000} onChange={e=>{setContext(e.target.value);setConfirmed(false);}}/></label><label><input type="checkbox" checked={confirmed} disabled={!canPopulation} onChange={e=>setConfirmed(e.target.checked)}/>我已核对以上条件，温度等于这份自由能的计算温度，所选项是同一体系中去重后的可比较构象。</label>
 <div className="table-scroll"><table><thead><tr><th>纳入集合</th><th>构象</th>{table.columns.map(c=><th key={c}>{c} / Eh</th>)}<th>集合内比例</th></tr></thead><tbody>{table.rows.map(r=><tr key={r.name}><td><input type="checkbox" aria-label={'纳入 '+r.name} checked={selected.includes(r.name)} onChange={e=>{setSelected(a=>e.target.checked?[...a,r.name]:a.filter(n=>n!==r.name));setConfirmed(false);}}/></td><td>{r.name}</td>{table.columns.map(c=><td key={c}>{r.values[c]}</td>)}<td>{pops.length&&selected.includes(r.name)?(pops[chosen.indexOf(r)]*100).toFixed(3)+'%':'—'}</td></tr>)}</tbody></table></div>
 <p>pᵢ = exp[−(Gᵢ−Gmin)/(RT)] / Σ exp[−(Gⱼ−Gmin)/(RT)]。只对勾选集合归一化；不自动增加自旋或简并权重，不代表已覆盖全部构象。</p><button onClick={()=>download('thermochemistry-comparison.csv',csv([['source_sha256',thermoSource?.sha256],['energy_column',column],['temperature_K',temp],['review_notes',context],['scope','selected set; no scientific acceptance'],['Structure',...table.columns,'selected','population'],...table.rows.map(r=>[r.name,...table.columns.map(c=>r.values[c]),selected.includes(r.name),pops.length&&selected.includes(r.name)?pops[chosen.indexOf(r)]:''])]),'text/csv;charset=utf-8')}>导出热化学与比例 CSV</button></>}
 </section></>;
}
