import {isGeometry} from './molecule-viewer';
import type {Geometry} from './molecule-viewer';
import {parseStructure} from './draft-model';
export type IRCPoint={branch:'forward'|'reverse';point:number;coordinate:number;energy_hartree:number;geometry:Geometry};
export type IRCData={schema:'autog-irc-trajectory/1';coordinate_units:'bohr*sqrt(amu)'|'angstrom*sqrt(amu)'|'point-index';points:IRCPoint[];endpoints?:{forward?:string;reverse?:string};scope?:string};
export function parseIRC(text:string,name:string):IRCData{
 let data:IRCData;
 if(/\.xyz$/i.test(name)){
  const lines=text.replace(/\r/g,'').split('\n');const points:IRCPoint[]=[];let i=0;while(i<lines.length&&lines[i].trim()){const n=Number(lines[i]),comment=lines[i+1];if(!Number.isInteger(n)||n<1||n>2000||!comment)throw Error('XYZ 轨迹帧无效。');const m=comment.match(/^irc=(forward|reverse) point=(\d+) coordinate=([^ ]+) energy_hartree=([^ ]+) units=(bohr\*sqrt\(amu\)|angstrom\*sqrt\(amu\)|point-index)$/);if(!m)throw Error('XYZ 注释必须含明确的 IRC 分支、点号、坐标、能量与单位；普通优化 XYZ 不作为 IRC。');const geometry=parseStructure(lines.slice(i,i+n+2).join('\n'),'frame.xyz').geometry;points.push({branch:m[1] as IRCPoint['branch'],point:Number(m[2]),coordinate:Number(m[3]),energy_hartree:Number(m[4]),geometry});if(points.length>1000)throw Error('最多导入 1000 个 IRC 点。');i+=n+2;}
  if(lines.slice(i).some(l=>l.trim()))throw Error('轨迹包含未读取内容。');const units=lines[1]?.match(/ units=(.+)$/)?.[1];if(points.length&&lines.filter(l=>l.startsWith('irc=')).some(l=>!l.endsWith('units='+units)))throw Error('轨迹单位变化。');data={schema:'autog-irc-trajectory/1',coordinate_units:units as IRCData['coordinate_units'],points};
 }else data=JSON.parse(text);
 if(!data||data.schema!=='autog-irc-trajectory/1'||!['bohr*sqrt(amu)','angstrom*sqrt(amu)','point-index'].includes(data.coordinate_units)||!Array.isArray(data.points)||data.points.length<2||data.points.length>1000)throw Error('需要带显式单位的 IRC 轨迹契约（2–1000 点）。');
 const seen=new Set<string>(),last:Partial<Record<IRCPoint['branch'],IRCPoint>>={};let sequence='';let atoms=0;
 for(const p of data.points){if(!p||!['forward','reverse'].includes(p.branch)||!Number.isSafeInteger(p.point)||p.point<0||typeof p.coordinate!=='number'||!Number.isFinite(p.coordinate)||p.coordinate<0||typeof p.energy_hartree!=='number'||!Number.isFinite(p.energy_hartree)||!isGeometry(p.geometry)||p.geometry.atoms.length>2000)throw Error('IRC 点字段、几何或有限数值无效。');atoms+=p.geometry.atoms.length;if(atoms>200000)throw Error('轨迹总原子数超过 200000。');const s=p.geometry.atoms.map(a=>a.atomic_number).join(',');if(sequence&&s!==sequence)throw Error('原子顺序或元素发生变化；不能连接轨迹。');sequence=s;const key=p.branch+':'+p.point,prev=last[p.branch];if(seen.has(key)||prev&&(p.point!==prev.point+1||p.coordinate<=prev.coordinate))throw Error('IRC 点重复、缺步或坐标不递增；请按连续分支分别导入。');seen.add(key);last[p.branch]=p;}
 if(data.endpoints&&(!['forward','reverse'].every(b=>data.endpoints?.[b as 'forward']===undefined||typeof data.endpoints?.[b as 'forward']==='string')))throw Error('端点标签无效。');return data;
}
export type ThermoRow={name:string;values:Record<string,number>};
export type ThermoTable={columns:string[];rows:ThermoRow[];preamble:string};
export function parseGoodVibes(text:string):ThermoTable{
 if(text.length>8*1024*1024)throw Error('文件超过 8 MiB。');const lines=text.replace(/\r/g,'').split('\n');const headers=lines.map((l,i)=>/^\s*Structure(?:\s|,)/.test(l)?i:-1).filter(i=>i>=0);if(headers.length!==1)throw Error('请导入单一温度/条件的 GoodVibes 表；多表应分别导出。');const h=headers[0],comma=lines[h].includes(','),split=(s:string)=>comma?s.split(',').map(x=>x.trim()):s.trim().split(/\s+/),columns=split(lines[h]);if(columns[0]!=='Structure'||new Set(columns).size!==columns.length||!columns.some(c=>/^qh-G\(T\)(?:_SPC)?$/.test(c)))throw Error('需要明确的 qh-G(T) 或 qh-G(T)_SPC 列；数值单位为 Hartree。');
 const rows:ThermoRow[]=[];let started=false;for(const line of lines.slice(h+1)){if(/^\s*\*{5,}/.test(line)){if(started)break;continue;}if(!line.trim()){if(started)break;continue;}let cells=split(line);if(['o','○'].includes(cells[0]))cells=cells.slice(1);if(cells[0]==='x'||cells[0]==='!')throw Error('表中有错误/排除标记，请核对来源后导出明确的有效集合。');if(cells.length!==columns.length)throw Error('表格列数不匹配，不能忽略异常行。');const values:Record<string,number>={};for(let j=1;j<columns.length;j++){if(!/^[+-]?(?:\d+\.?\d*|\.\d+)(?:[EeDd][+-]?\d+)?$/.test(cells[j]))throw Error('表格含缺失或非数值字段。');const n=Number(cells[j].replace(/[dD]/,'e'));if(!Number.isFinite(n))throw Error('非有限能量。');values[columns[j]]=n;}if(!cells[0]||rows.some(r=>r.name===cells[0]))throw Error('结构名称为空或重复。');rows.push({name:cells[0],values});started=true;if(rows.length>2000)throw Error('最多导入 2000 个构象。');}
 if(!rows.length)throw Error('未找到有效数据行。');return {columns:columns.slice(1),rows,preamble:lines.slice(0,h).join('\n')};
}
// G is already a free energy. Do not multiply in an implicit spin/degeneracy factor.
export function populations(values:number[],temperature:number){if(values.length<2||values.some(x=>!Number.isFinite(x))||!Number.isFinite(temperature)||temperature<=0||temperature>10000)throw Error('需要至少两个有限 G 和明确的 0<T≤10000 K。');const min=Math.min(...values),weights=values.map(g=>Math.exp(-(g-min)*2625499.6394799/(8.31446261815324*temperature))),sum=weights.reduce((a,b)=>a+b,0);return weights.map(w=>w/sum);}
