import {SelectResult,SelectionActions} from './result-selection';
import {routeLink} from './navigation';
import {ArchiveStatus,StatusLegend} from './status-badge';
import {useEffect,useState} from 'react';
import {requestJSON,read} from './contract';
import type {Attempt} from './contract';
import {useCollection,Filters,Pagination,AttemptsBrowser} from './browse';
import {collections,collectionValue,findCollection,useOrganization} from './project-organization';
import type {Group,Collection,Organization,Bucket} from './project-organization';
import './project-organization.css';
type Archive={archive_id:string;title:string;parser:{status:string};summary:null|{energy_hartree:number|null;frequency_count:number|null;imaginary_count:number|null;termination:string}};
function groups(v:unknown):Group[]{const d=v as {schema:string;items:Group[]};if(d.schema!=='autog-project-library/1'||!Array.isArray(d.items)||!d.items.every(x=>typeof x.id==='string'&&typeof x.label==='string'&&typeof x.source_label==='string'&&['native','historical'].includes(x.kind)&&Number.isSafeInteger(x.count)&&Array.isArray(x.states)&&(x.archive_ids===undefined||Array.isArray(x.archive_ids)&&x.archive_ids.every(id=>/^archive-[a-f0-9]{64}$/.test(id)))))throw Error('contract-mismatch');return d.items;}
export function ProjectLibrary({token,id,results=false,testsOnly=false,resultProject,revision=0,sourceFilter='all'}:{token:string;id?:string;results?:boolean;testsOnly?:boolean;resultProject?:string;revision?:number;sourceFilter?:string}){
 const [items,setItems]=useState<Group[]|null>(null),[selected,setSelected]=useState(()=>{try{return resultProject??(results?sessionStorage.getItem('autog-results-project')??'':'');}catch{return resultProject??'';}}),[error,setError]=useState('');
 const [retry,setRetry]=useState(0),[loading,setLoading]=useState(true),[slow,setSlow]=useState(false),[snapshot,setSnapshot]=useState<{content_sha256?:string;read_at?:string;latest_archive_capture?:string|null}>({});
 const org=useOrganization();const bucket:Bucket=testsOnly?'test':'calculation';
 const [resultBucket,setResultBucket]=useState<Bucket|'all'>(()=>{try{const saved=sessionStorage.getItem('autog-results-purpose');return saved==='test'||saved==='all'?saved:'calculation';}catch{return 'calculation';}});
 useEffect(()=>{if(results)try{sessionStorage.setItem('autog-results-purpose',resultBucket);}catch{}},[resultBucket,results]);
 const scoped=(items??[]).filter(g=>results?resultBucket==='all'||org.info(g).bucket===resultBucket:org.info(g).bucket===bucket).filter(g=>results||sourceFilter==='all'||g.kind===sourceFilter);
 const organized=collections(scoped,org.prefs);
 const c=useCollection(organized,x=>({id:x.id,name:x.name,pinned:x.pinned,search:[x.name,...x.groups.flatMap(g=>[g.label,g.id,g.source_label])].join(' '),states:x.states,programs:[]}),testsOnly?'test-project-library':'project-library');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setSlow(false);setError('');
 const slowTimer=setTimeout(()=>setSlow(true),3000),timeout=setTimeout(()=>controller.abort('timeout'),15000);let disposed=false;
 requestJSON('/api/project-library',token,controller.signal).then(v=>{const next=groups(v);if(!disposed){setItems(next);const meta=(v as {snapshot?:typeof snapshot}).snapshot;setSnapshot(meta??{});}}).catch(e=>{if(!disposed)setError(e instanceof Error?e.message:'读取失败');}).finally(()=>{if(!disposed)setLoading(false);clearTimeout(slowTimer);clearTimeout(timeout);});
 return()=>{disposed=true;controller.abort();clearTimeout(slowTimer);clearTimeout(timeout);};},[token,revision,retry]);
 useEffect(()=>{if(results)try{sessionStorage.setItem('autog-results-project',selected);}catch{}},[results,selected]);
 const active=id??selected,group=items?.find(x=>x.id===active);
 const allCollections=collections(items??[],org.prefs),series=active.startsWith('series:')?findCollection(allCollections,active):undefined,parent=findCollection(allCollections,active);
 const chooseScope=(value:string)=>{setSelected(value);if(!value){setResultBucket('all');try{sessionStorage.setItem('autog-results-purpose','all');}catch{}}location.hash=id&&value?'#/history-projects/'+encodeURIComponent(value):'#/results?project='+encodeURIComponent(value);};
 return <><div className="page-heading"><div className="eyebrow">{results?'SCIENCE / RESULTS':testsOnly?'SANDBOX / VALIDATION':'RESEARCH / PROJECTS'}</div><h1>{results?'科学结果':testsOnly?'测试与验收':'项目库'}</h1><p>{results?'集中查看能量、频率与计算状态，打开记录查看结构和原始日志。':'原生计算项目与历史目录分组集中浏览。任务按目录系列整理，历史归类不改变 Core 项目关系。'}</p></div><div className="read-time">{results?'科学数据索引 · 同一日志只列一次':'项目目录 · 独立只读索引'} <a href="#/workflows">查看运行总览 →</a></div>
 <details className="index-freshness"><summary>索引时间与来源</summary>索引读取时间：{snapshot.read_at??'未提供'}<br/>最近归档捕获：{snapshot.latest_archive_capture??'未提供'}（不是计算完成时间）<details><summary>索引内容指纹</summary><code>{snapshot.content_sha256??'当前服务未提供'}</code><p>标识本次浏览索引内容；Core 与档案分别读取，不保证包含尚未入库的回收结果。</p></details></details>
 {!results&&!id&&<p className="micro">Phase 0 只读浏览：创建、暂停/恢复、归档、删除、复制尚未开放。计划以 Attempt 精确绑定为准；审批与待办汇总尚未接入。</p>}
 {loading&&<p role="status">{items?'正在刷新，保留上次成功快照…':'读取项目…'}{slow?'读取较慢，请稍候；15 秒后可重试。':''}</p>}
 {error&&<div className="notice warning" role="alert">项目索引读取失败。{{unauthorized:'只读令牌无效', 'not-found':'未找到这条记录','invalid-evidence':'证据结构无法通过校验','response-too-large':'数据超过本版读取上限','store-unavailable':'当前数据源不可读取','contract-mismatch':'接口不符合查询契约'}[error]??'请检查本地服务或网络。'}{items?'正在显示上次成功快照，可能已过期。':'尚无可展示快照。'}<button onClick={()=>setRetry(v=>v+1)}>重试项目索引</button></div>}
 {items&&<>
 {org.error&&<p className="notice warning" role="alert">{org.error}</p>}
 {!results&&!id&&<><label>来源筛选<select aria-label="项目来源" value={sourceFilter} onChange={e=>{location.hash=routeLink('#/projects',{source:e.target.value,purpose:testsOnly?'test':undefined});}}><option value="all">全部来源</option><option value="native">原生项目</option><option value="historical">历史目录</option></select></label><div className="project-partitions"><a href="#/projects" aria-current={!testsOnly?'page':undefined}>计算记录 <b>{allCollections.filter(c=>c.bucket==='calculation').length} 组</b></a><a href="#/projects?purpose=test" aria-current={testsOnly?'page':undefined}>测试 / 验收 <b>{allCollections.filter(c=>c.bucket==='test').length} 组</b></a><small>按目录名称初分，可在“整理”中调整</small></div><p className="micro">项目名称用于浏览整理；自动系列不是已核实的科研项目。整理偏好保存在当前浏览器，不移动文件。</p></>}
 {(results||id)&&<div className="science-scope"><label>项目范围<select aria-label="结果项目" value={parent?collectionValue(parent):active} onChange={e=>chooseScope(e.target.value)}><option value="">全部归档结果</option>{allCollections.filter(c=>!id||c.kind==='historical').map(c=><option key={c.id} value={collectionValue(c)}>{c.pinned?'📌 ':''}{c.bucket==='test'?'测试 · ':''}{c.name}（{c.groups.length} 个任务）</option>)}</select></label>{parent&&parent.groups.length>1&&<label>项目内任务<select aria-label="项目内任务" value={group?.id??''} onChange={e=>chooseScope(e.target.value||collectionValue(parent))}><option value="">全部 {parent.groups.length} 个任务</option>{parent.groups.map(g=><option key={g.id} value={g.id}>{g.label}（{g.count} 份结果）</option>)}</select></label>}{results&&<label>用途<select aria-label="结果用途" value={parent?.bucket??resultBucket} onChange={e=>{setResultBucket(e.target.value as Bucket|'all');setSelected('');if(resultProject!==undefined){try{sessionStorage.setItem('autog-results-purpose',e.target.value);}catch{}location.hash='#/results?project=';}}}><option value="all">全部用途</option><option value="calculation">计算记录</option><option value="test">测试 / 验收</option></select></label>}<a href="#/projects">项目整理 ↗</a></div>}
 {group?<ProjectEntries key={group.kind+group.id+revision} group={group} token={token}/>:series?<ScienceIndex key={revision} token={token} groups={series.groups} allGroups={items} organization={org.info}/>:id||active?<p className="notice warning">所选项目不在当前索引中，请重新选择。</p>:results?<ScienceIndex key={revision} token={token} groups={scoped} allGroups={items} organization={org.info}/>:<><p className="micro">筛选轴：大写状态为 Core 执行记录；parsed / partial / unparseable 为解析状态；termination 为日志终止。审批和科学验证未纳入筛选。</p><Filters collection={c} label="搜索项目" programs={false} stateLabel="执行 / 解析 / 终止状态"/><div className="organized-projects">{c.rows.map(g=><CollectionCard key={g.id+c.state} collection={g} save={org.change} pin={(groups,value)=>{org.pin(groups,value);c.setPage(1);}} state={c.state}/>)}</div>{!c.rows.length&&<p className="empty compact">此分区没有匹配项目。</p>}<Pagination collection={c} unit="个项目"/></>}
 </>}
 </>;
}
function CollectionCard({collection:c,save,pin,state}:{collection:Collection;state:string;pin:(groups:Group[],value:boolean)=>void;save:(groups:Group[],value:Organization|null)=>void}){
 const first=c.groups[0],single=c.groups.length===1;
 const members=useCollection(c.groups.filter(g=>!state||g.states.includes(state)),g=>({id:g.id,name:g.label,search:g.label,states:g.states,programs:[]}));
 const issues=c.kind==='historical'?new Set(c.groups.flatMap(g=>g.issue_archive_ids??[])).size:c.groups.reduce((n,g)=>n+(g.issue_count??0),0);
 const coverage=c.groups.every(g=>g.state_counts);
 const states=(g:Group)=>g.states.map(s=>s+' × '+(g.state_counts?.[s]??'未知')).join(' · ');
 const href=(g:Group)=>g.kind==='native'?`#/projects/${encodeURIComponent(g.id)}`:`#/history-projects/${encodeURIComponent(g.id)}${state?"?state="+encodeURIComponent(state):""}`;
 return <article className="project-card organized-card"><div className="organized-card-head"><div><span className={'purpose-label '+(c.bucket==='test'?'purpose-test':'purpose-calculation')}>{c.bucket==='test'?'测试 / 验收':'计算记录'}</span><h2><a href={single?href(first):'#/history-projects/'+encodeURIComponent(collectionValue(c))}>{c.name} ↗</a></h2><button className="pin-project" aria-label={(c.pinned?'取消置顶项目 ':'置顶项目 ')+c.name} aria-pressed={c.pinned} onClick={()=>pin(c.groups,!c.pinned)}>{c.pinned?'📌 已置顶':'置顶'}</button></div><span className="organized-count"><b>{c.count}</b> {c.kind==='native'?'历史尝试':'份结果'}<small>{c.groups.length} {c.kind==='native'?'个原生项目':'个任务目录'}</small></span></div>
 <p className="micro">{c.kind==='native'?`原生 Project → ${c.groups.reduce((n,g)=>n+(g.task_count??0),0)} Tasks → ${c.count} 历史 Attempts`:c.groups.length>1?'项目下的任务 · 保留各任务原始来源':'历史目录 · 未绑定原生 Task'}</p>
 <p className="micro">异常 / 待核对历史成员：{coverage?issues:'当前索引未提供'}{state?' · 当前匹配：'+state:''}</p>
 {single&&<p className="member-states">{states(first)}</p>}
 {!single&&<details className="collection-members" open={state?true:undefined}><summary>展开 {c.groups.length} 个任务</summary><div className="member-list">{members.rows.map(g=><div className="member-row" key={g.id}><a href={href(g)}>{g.label} ↗</a><span>{g.count} 份归档结果</span><span className="member-states">{states(g)}</span><span>来源：{g.source_label}</span><Organize groups={[g]} current={{project:c.name,bucket:c.bucket,pinned:c.pinned}} save={save}/></div>)}</div><Pagination collection={members} unit="个匹配目录"/></details>}

 <div className="organized-actions">{!single&&c.kind==='historical'&&<a href={'#/results?project='+encodeURIComponent('series:'+c.id)}>查看项目全部结果 →</a>}{single&&<a href={'#/results?project='+encodeURIComponent(first.id)}>查看科学结果 →</a>}<Organize groups={c.groups} current={{project:c.name,bucket:c.bucket,pinned:c.pinned}} save={save}/></div>
 </article>;
}
function Organize({groups,current,save}:{groups:Group[];current:Organization;save:(groups:Group[],value:Organization|null)=>void}){
 const [name,setName]=useState(current.project),[bucket,setBucket]=useState(current.bucket);
 return <details className="organize-editor"><summary>{groups.length>1?'重命名 / 整理项目':'重命名 / 整理'}</summary><form onSubmit={e=>{e.preventDefault();if(name.trim())save(groups,{project:name.trim(),bucket,pinned:current.pinned});}}><label>展示项目名称<input aria-label="展示项目名称" value={name} maxLength={100} required onChange={e=>setName(e.target.value)}/></label><label>用途分区<select aria-label="用途分区" value={bucket} onChange={e=>setBucket(e.target.value as Bucket)}><option value="calculation">计算记录</option><option value="test">测试 / 验收</option></select></label><button type="submit">保存整理</button><button type="button" onClick={()=>save(groups,null)}>恢复目录归类</button><small>仅保存浏览器显示偏好，不改变原始项目或科学记录。</small></form></details>;
}
function ScienceIndex({token,groups,allGroups,organization}:{token:string;groups:Group[];allGroups:Group[];organization:(g:Group)=>Organization}){
 const [archives,setArchives]=useState<Archive[]|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const ac=new AbortController();requestJSON('/api/archives',token,ac.signal).then(v=>{const d=v as {schema:string;items:Archive[]};if(d.schema==='auto-g16-legacy-archive/1'&&Array.isArray(d.items)&&d.items.some(a=>(a as Archive & {source_kind?:string}).source_kind==='local_log_archive'))throw Error();if(!['auto-g16-legacy-archive/1','auto-g16-legacy-archive/2'].includes(d.schema)||!Array.isArray(d.items)||!d.items.every(a=>/^archive-[a-f0-9]{64}$/.test(a.archive_id)&&typeof a.title==='string'&&a.parser))throw Error();if(!ac.signal.aborted)setArchives(d.items);}).catch(()=>{if(!ac.signal.aborted)setError(true);});return()=>ac.abort();},[token]);
 const visible=new Set(groups.flatMap(g=>g.archive_ids??[])),known=new Set(allGroups.flatMap(g=>g.archive_ids??[])),scopeAll=groups.length===allGroups.length;
 const rows=(archives??[]).filter(a=>visible.has(a.archive_id)||scopeAll&&!known.has(a.archive_id)).map(a=>({...a,members:groups.filter(g=>g.archive_ids?.includes(a.archive_id))}));
 const c=useCollection(rows,a=>({id:a.archive_id,name:a.title,search:[a.title,a.archive_id,...a.members.flatMap(g=>[g.label,organization(g).project])].join(' '),states:[a.parser.status,...(a.summary?[a.summary.termination]:[])],programs:['Gaussian']}),'science-index');
 if(error)return <p role="alert">科学结果索引无法读取。</p>;if(!archives)return <p>读取科学结果…</p>;
 return <section className="panel science-index"><div className="science-index-head"><h2>归档结果 <small>{rows.length} 份独立日志</small></h2><span>原生 Attempt 结果请在上方选择项目</span></div><SelectionActions/><StatusLegend/><Filters collection={c} label="搜索科学结果"/><div className="table-scroll"><table><thead><tr><th>选择</th><th>项目</th><th>计算记录</th><th>计算状态</th><th>能量 / Hartree</th><th>频率 / 虚频</th></tr></thead><tbody>{c.rows.map(a=><tr key={a.archive_id}><td><SelectResult item={{kind:'archive',id:a.archive_id,title:a.title,project:a.members[0]?.id}}/></td><td>{[...new Set(a.members.map(g=>organization(g).project.replace(/ · 目录系列$/,'')))].join(' · ')||'未归类'}<small>{a.members.some(g=>organization(g).bucket==='test')?'含测试 / 验收归类':'计算记录'}</small></td><td><a href={'#/archives/'+a.archive_id+(a.members[0]?'?from='+encodeURIComponent(a.members[0].id):'')}>{a.title}</a></td><td><ArchiveStatus status={a.parser.status} termination={a.summary?.termination}/></td><td>{a.summary?.energy_hartree??'未解析'}</td><td>{a.summary?.frequency_count??'—'} / {a.summary?.imaginary_count??'—'}</td></tr>)}</tbody></table></div><Pagination collection={c} unit="份独立日志"/></section>;
}
function ProjectEntries({group,token}:{group:Group;token:string}){
 const [archives,setArchives]=useState<Archive[]>([]),[attempts,setAttempts]=useState<Attempt[]|null>(null),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const c=useCollection(archives,x=>({id:x.archive_id,name:x.title,search:[x.title,x.archive_id].join(' '),states:[x.parser.status,...(x.summary?[x.summary.termination]:[])],programs:['Gaussian']}), 'project-results:'+group.id);
 useEffect(()=>{const state=new URLSearchParams(location.hash.split('?')[1]??'').get('state');if(state)c.setState(state);},[group.id]);
 useEffect(()=>{const ac=new AbortController();async function load(){try{if(group.kind==='native'){const d=await read(`/api/projects/${encodeURIComponent(group.id)}/attempts`,'attempts',token,ac.signal);if(d.items.some(a=>a.project_id!==group.id))throw Error('identity');if(!ac.signal.aborted)setAttempts(d.items);}else{const d=await requestJSON(`/api/project-library/${encodeURIComponent(group.id)}`,token,ac.signal) as {schema:string;project:Group;items:Archive[]};if(d.schema!=='autog-project-library/1'||d.project.id!==group.id||!Array.isArray(d.items)||!d.items.every(x=>typeof x.title==='string'&&/^archive-[a-f0-9]{64}$/.test(x.archive_id)))throw Error();if(!ac.signal.aborted)setArchives(d.items);}if(!ac.signal.aborted)setLoaded(true);}catch{if(!ac.signal.aborted)setError('读取失败');}}void load();return()=>ac.abort();},[group.id,group.kind,token]);
 if(error)return <p role="alert">项目结果索引无法读取。</p>;if(!loaded)return <p>读取项目结果…</p>;if(attempts)return <AttemptsBrowser token={token} attempts={attempts}/>;
 return <section className="panel"><h2>{group.label}</h2><SelectionActions/><StatusLegend/><Filters collection={c} label="搜索项目结果"/><div className="table-scroll"><table><thead><tr><th>计算记录</th><th>日志状态</th><th>能量 / Hartree</th><th>频率 / 虚频</th></tr></thead><tbody>{c.rows.map(x=><tr key={x.archive_id}><td><SelectResult item={{kind:'archive',id:x.archive_id,title:x.title,project:group.id}}/> <a href={'#/archives/'+x.archive_id+'?from='+encodeURIComponent(group.id)}>{x.title}</a></td><td><ArchiveStatus status={x.parser.status} termination={x.summary?.termination}/></td><td>{x.summary?.energy_hartree??'不可用'}</td><td>{x.summary?.frequency_count??'未记录'} / {x.summary?.imaginary_count??'未知'}</td></tr>)}</tbody></table></div><Pagination collection={c}/></section>;
}
