import {useSessionValue,routeLink,routeParams} from './navigation';
import {parseSelection} from './result-selection';
import type {SelectedResult} from './result-selection';
import {collections,collectionValue,findCollection,useOrganization} from './project-organization';
import type {Group} from './project-organization';
import {ComparisonPanel} from './comparison-panel';
import {useEffect,useMemo,useState} from 'react';
import {read,requestJSON} from './contract';
import {parseDetails} from './detail-panel';
import {scientificFacts,screenCandidate} from './scientific-assessment';
import {isGeometry,MoleculeViewer} from './molecule-viewer';
import {object} from './provenance';
import {taskAction} from './task-center';

type Row=SelectedResult & {status:string;energy:number|null};
const rowKey=(r:SelectedResult)=>r.kind+':'+r.id;
type Detail=ReturnType<typeof parseDetails>;
const title:Record<string,string>={MINIMUM_CANDIDATE:'极小值候选',TS_CANDIDATE:'TS 候选 · 待确认方向',NOT_FIRST_ORDER:'多个虚频',PROGRAM_FAILED:'程序失败',FREQUENCY_INCOMPLETE:'频率不完整',EVIDENCE_INCOMPLETE:'驻点证据不足',EVIDENCE_UNAVAILABLE:'证据不可用'};
function energy(d:Detail|undefined,metric:string){const data=d?.result.data;if(!data)return null;const v=metric==='E'?data.final_energy_hartree:object(data.thermochemistry)&&object(data.thermochemistry.sum_electronic_gibbs_hartree)?data.thermochemistry.sum_electronic_gibbs_hartree.value_hartree:null;return typeof v==='number'&&Number.isFinite(v)?v:null;}
function composition(d:Detail|undefined){const g=d?.result.data?.last_geometry;if(!isGeometry(g))return null;return g.atoms.map(a=>a.atomic_number).sort((a,b)=>a-b).join(',');}
export function ScreeningPanel({token,projectId='',initialSelection=[]}:{token:string;projectId?:string;initialSelection?:SelectedResult[]}){
 const org=useOrganization();
 const [routeScopes]=useState<string[]|null>(()=>{try{const v=JSON.parse(routeParams().get('projects')??'null');return Array.isArray(v)&&v.length<=100&&v.every(x=>typeof x==='string')?v:null;}catch{return null;}});
 const [groups,setGroups]=useState<Group[]>([]),[rows,setRows]=useState<Row[]>([]),[details,setDetails]=useState<Record<string,Detail>>({}),[failures,setFailures]=useState<string[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const [scopes,setScopes]=useSessionValue<string[]>('screen-project-scopes/2',projectId?[projectId]:[]),[selectionOnly,setSelectionOnly]=useState(initialSelection.length>0);
 const [savedSelection,setSavedSelection]=useSessionValue<SelectedResult[]>('screen-selected-records/2',initialSelection);
 const checkedRecords=parseSelection(JSON.stringify(savedSelection)),checked=checkedRecords.map(rowKey);
 const [filter,setFilter]=useState('all'),[search,setSearch]=useSessionValue('screen-search:'+projectId+':'+initialSelection.map(r=>r.id).join('|'),''),[page,setPage]=useSessionValue('screen-page:'+projectId+':'+initialSelection.map(r=>r.id).join('|'),0),[selected,setSelected]=useSessionValue('screen-active:'+projectId,''),[metric,setMetric]=useState('E'),[comparable,setComparable]=useState(false),[stage,setStage]=useState('optimization'),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const projects=collections(groups,org.prefs),scopeProjects=projects.filter(c=>Array.isArray(scopes)&&scopes.some(id=>findCollection(projects,id)?.id===c.id));
 const scopeGroups=[...new Map(scopeProjects.flatMap(c=>c.groups).map(g=>[g.id,g])).values()],scopeKey=scopeGroups.map(g=>g.id).sort().join('|');
 useEffect(()=>{if(initialSelection.length)setSavedSelection(initialSelection);},[]);
 useEffect(()=>{const c=new AbortController();requestJSON('/api/project-library',token,c.signal).then(v=>{if(!object(v)||v.schema!=='autog-project-library/1'||!Array.isArray(v.items)||!v.items.every(g=>object(g)&&typeof g.id==='string'&&typeof g.label==='string'&&typeof g.source_label==='string'&&Array.isArray(g.states)&&['native','historical'].includes(String(g.kind))))throw Error();if(c.signal.aborted)return;const gs=v.items as Group[],cs=collections(gs,org.prefs);setGroups(gs);const wanted=projectId?[projectId]:routeScopes??(Array.isArray(scopes)?scopes:[]),valid=wanted.map(id=>findCollection(cs,id)).filter(x=>!!x).map(collectionValue);setScopes(valid.length?Array.from(new Set(valid)):routeScopes!==null?[]:cs[0]?[collectionValue(cs[0])]:[]);}).catch(()=>{if(!c.signal.aborted)setError('项目索引读取失败。');});return()=>c.abort();},[token]);
 useEffect(()=>{if(selectionOnly){setRows(initialSelection.map(r=>({...r,status:'已选记录',energy:null})));setLoading(false);return;}if(!groups.length)return;const c=new AbortController();setRows([]);setError('');setComparable(false);setMessage('');setLoading(true);
 const load=async(g:Group):Promise<Row[]>=>{if(g.kind==='native'){const d=await read(`/api/projects/${encodeURIComponent(g.id)}/attempts`,'attempts',token,c.signal);if(d.items.some(a=>a.project_id!==g.id))throw Error('identity');return d.items.map(a=>({id:a.attempt_id,kind:'attempt',title:a.attempt_id,project:g.id,status:a.execution_state,energy:null}));}const v=await requestJSON(`/api/project-library/${encodeURIComponent(g.id)}`,token,c.signal);if(!object(v)||v.schema!=='autog-project-library/1'||!object(v.project)||v.project.id!==g.id||!Array.isArray(v.items))throw Error();return v.items.map(a=>{if(!object(a)||typeof a.archive_id!=='string'||typeof a.title!=='string'||!object(a.parser))throw Error();return {id:a.archive_id,kind:'archive',title:a.title,project:g.id,status:String(object(a.summary)?a.summary.termination:a.parser.status),energy:object(a.summary)&&typeof a.summary.energy_hartree==='number'?a.summary.energy_hartree:null};});};
 void Promise.allSettled(scopeGroups.map(load)).then(found=>{if(c.signal.aborted)return;const values=found.flatMap(v=>v.status==='fulfilled'?v.value:[]);setRows([...new Map(values.map(r=>[rowKey(r),r])).values()]);const missing=found.flatMap((v,i)=>v.status==='rejected'?[scopeGroups[i].label]:[]);if(missing.length)setError('以下任务读取失败，当前列表不完整：'+missing.join('、'));setLoading(false);});return()=>c.abort();},[scopeKey,selectionOnly,token]);
 function chooseProjects(ids:string[]){setScopes(ids);setSelectionOnly(false);setPage(0);setSelected('');location.hash=routeLink('#/analysis',{tab:'compare',project:ids.length===1?ids[0]:undefined,projects:ids.length===1?undefined:JSON.stringify(ids)});}
 function toggleResult(r:SelectedResult,on:boolean){setSavedSelection(prev=>on?[...parseSelection(JSON.stringify(prev)).filter(v=>rowKey(v)!==rowKey(r)),{kind:r.kind,id:r.id,title:r.title,project:r.project}].slice(0,100):parseSelection(JSON.stringify(prev)).filter(v=>rowKey(v)!==rowKey(r)));setComparable(false);}
 const filtered=useMemo(()=>rows.filter(r=>(r.title+' '+r.id).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||['FAILED','UNKNOWN','error-termination','unparseable','partial','unknown'].includes(r.status))),[rows,filter,search]);
 const pageRows=filtered.slice(page*10,page*10+10),pageKey=pageRows.map(rowKey).join('|');
 useEffect(()=>{const c=new AbortController();setComparable(false);const load=async()=>{for(const r of [...new Map([...pageRows,...checkedRecords].map(r=>[rowKey(r),r])).values()]){if(details[rowKey(r)]||failures.includes(rowKey(r)))continue;try{const v=await requestJSON(`/api/${r.kind==='archive'?'archives':'attempts'}/${encodeURIComponent(r.id)}/details`,token,c.signal);const d=parseDetails(v,r.kind,r.id);if(!c.signal.aborted)setDetails(prev=>({...prev,[rowKey(r)]:d}));}catch{if(!c.signal.aborted)setFailures(prev=>[...prev,rowKey(r)]);}if(c.signal.aborted)return;}};void load();return()=>c.abort();},[pageKey,checked.join('|'),token]);
 const active=rows.find(r=>rowKey(r)===selected)??pageRows[0],detail=active?details[rowKey(active)]:undefined;
 const selectedRows=checkedRecords,compositions=selectedRows.map(r=>composition(details[rowKey(r)]));
 const compatible=selectedRows.length>=2&&compositions.every(c=>c!==null&&c===compositions[0])&&selectedRows.every(r=>energy(details[rowKey(r)],metric)!==null);
 const baseline:number|null=null;
 const displayRows=pageRows;
 async function draft(){if(!active||!detail||saving)return;const source=detail.result.source;if(!source||!object(source.artifact)||typeof source.artifact.sha256!=='string'){setMessage('缺少结果来源，不能创建候选草稿。');return;}setSaving(true);setMessage('');try{await taskAction('draft',{request_id:crypto.randomUUID(),source:{kind:active.kind,id:active.id,sha256:source.artifact.sha256},stage,title:active.title.slice(0,160)},token);setMessage('草稿已保存到任务中心；尚未准备或提交计算。');}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setSaving(false);}}
 return <><div className="page-heading"><div className="eyebrow">CANDIDATE SCREENING</div><h1>筛选与比较</h1><p>查看逐项候选提示、比较选中结构，准备下一阶段草稿。</p></div>{error&&<p role="alert">{error}</p>}
 <div className="candidate-toolbar"><label>项目／候选集合<select value={scopeProjects.length===1?collectionValue(scopeProjects[0]):''} onChange={e=>{if(e.target.value)chooseProjects([e.target.value]);}}><option value="" disabled>{scopeProjects.length>1?'已选 '+scopeProjects.length+' 个项目':'选择项目'}</option>{projects.map(c=><option key={c.id} value={collectionValue(c)}>{c.pinned?'📌 ':''}{c.name}（{c.groups.length} 个任务）</option>)}</select></label><details className="screen-project-picker"><summary>选择多个项目（{scopeProjects.length}）</summary><div>{projects.map(c=><label key={c.id}><input type="checkbox" aria-label={'包含项目 '+c.name} checked={scopeProjects.some(p=>p.id===c.id)} onChange={e=>chooseProjects(e.target.checked?[...scopeProjects.map(collectionValue),collectionValue(c)]:scopeProjects.filter(p=>p.id!==c.id).map(collectionValue))}/>{c.name}<small>{c.groups.length} 个任务</small></label>)}</div></details>{selectionOnly&&<span>承接已选 {initialSelection.length} 条结果 <button onClick={()=>chooseProjects(scopeProjects.map(collectionValue))}>添加项目任务</button></span>}<label hidden>筛选<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);setSelected('');}}><option value="all">全部记录</option><option value="issues">报错或状态待核对</option></select></label><label>搜索候选<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);setSelected('');}}/></label><label>比较能量<select aria-label="比较能量" value={metric} onChange={e=>{setMetric(e.target.value);setComparable(false);}}><option value="E">电子能 E</option><option value="G">电子能 + Gibbs 校正 G</option></select></label></div>
 <p className="operations-note">候选提示复用现有频率筛查规则；构象搜索的聚类与淘汰理由仅在有相应来源时才可提供。每页展示 10 个候选，选中项跨任务、跨项目和跨页保留；比较范围仅限勾选项。</p>
 {checkedRecords.length>0&&<div className="selection-actions screen-selection" aria-label="比较已选结果"><strong>已选 {checkedRecords.length} 条结果</strong><button onClick={()=>{setSavedSelection([]);setComparable(false);}}>清除比较选择</button><details><summary>查看 / 移除已选项</summary>{checkedRecords.map(r=><div key={rowKey(r)}>{findCollection(projects,r.project??'')?.name??'来源项目待核对'} · {r.title}<button aria-label={'移除比较 '+r.title} onClick={()=>toggleResult(r,false)}>移除</button></div>)}</details><small>切换查看范围不会取消已选结果；最多 100 条。</small></div>}
 {loading?<p role="status">读取候选集合…</p>:<div className="candidate-layout"><section className="panel"><div className="table-scroll"><table><thead><tr><th>比较</th><th>项目 / 任务 / 结果</th><th>执行／初筛</th><th>{metric} / Hartree</th></tr></thead><tbody>{displayRows.map(r=>{const d=details[rowKey(r)],facts=scientificFacts(d?.result.data,d?.result.source),screen=screenCandidate(facts),e=energy(d,metric);return <tr key={rowKey(r)} className={active&&rowKey(active)===rowKey(r)?'candidate-row-selected':''}><td><input type="checkbox" aria-label={`比较 ${r.title}`} checked={checked.includes(rowKey(r))} disabled={!checked.includes(rowKey(r))&&checkedRecords.length>=100} onChange={event=>toggleResult(r,event.target.checked)}/></td><td><small>{findCollection(projects,r.project??'')?.name??'未归类'} / {groups.find(g=>g.id===r.project)?.label??'来源任务待核对'}</small><button onClick={()=>{setSelected(rowKey(r));setMessage('');}}>{r.title}</button></td><td><small>{r.status}</small><span>{failures.includes(rowKey(r))?'证据读取失败':!d?'读取证据…':title[screen.code]}</span></td><td>{e??'未记录'}</td></tr>;})}</tbody></table></div>{!pageRows.length&&<p>当前集合中没有匹配记录。</p>}
 <div className="task-actions"><button disabled={page===0} onClick={()=>{setPage(n=>n-1);setSelected('');}}>上一页</button><span>{filtered.length} 条 · 第 {page+1} 页</span><button disabled={(page+1)*10>=filtered.length} onClick={()=>{setPage(n=>n+1);setSelected('');}}>下一页</button></div>
 <p className="operations-note">勾选至少两个候选后，在下方条件比较中核对缺失或冲突，再计算相对能量。</p></section>
 <section className="panel">{!active?<p>选择候选以查看结构。</p>:<><h2>{active.title}</h2><a href={`#/${active.kind==='archive'?'archives':'attempts'}/${encodeURIComponent(active.id)}${active.kind==='archive'&&active.project?'?from='+encodeURIComponent(active.project):''}`}>打开计算详情 →</a>{detail?<><p>{screenCandidate(scientificFacts(detail.result.data,detail.result.source)).reason}</p><MoleculeViewer last={detail.result.data?.last_geometry} review={null}/><p className="candidate-source">日志 SHA-256：{object(detail.result.source?.artifact)?String(detail.result.source?.artifact.sha256):'不可用'}</p><div className="candidate-toolbar"><label>下一阶段<select value={stage} onChange={e=>setStage(e.target.value)}><option value="optimization">优化</option><option value="frequency">频率</option><option value="single-point">单点能</option><option value="review">人工审核</option></select></label><button disabled={saving||!detail.result.source} onClick={()=>void draft()}>保存计算草稿</button></div>{message&&<p role="status">{message}</p>}<a href="#/task-center">前往任务中心 →</a></>:<p>{failures.includes(rowKey(active))?'候选证据不可用。':'正在读取结构与筛查证据…'}</p>}</>}</section></div>}<ComparisonPanel token={token} metric={metric} items={selectedRows.filter(r=>details[rowKey(r)]).map(r=>({...r,detail:details[rowKey(r)]}))}/>
 </>;
}
